---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade, ONTAP tools, VMware vSphere, HA, non-HA, low RPO backup, SRA adapter, vCenter Server 
summary: 使用必要的預檢查和備份步驟，將 VMware vSphere 的 ONTAP tools 從 10.4 或 10.5 升級至 10.6，以支援 HA 和非 HA 部署。 
---
= 將 ONTAP tools for VMware vSphere 10.x 升級至 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以直接將 ONTAP tools for VMware vSphere 10.4 或 10.5 升級至 10.6。若要從 ONTAP tools 10.0、10.1、10.2 或 10.3 升級至 10.6，請先升級至 10.4 或 10.5。

[NOTE]
====
* 對於 ASA r2 系統，在設定更多儲存可用度區域 （SAZ） 之前，請確保將 ONTAP tools for VMware vSphere 升級至 10.6，並將 ONTAP 升級至 9.16.1。
* 如果從 ONTAP tools for VMware vSphere 10.4 或 10.5 升級至 10.6 失敗，則無法回復。請使用低 RPO 或快照恢復來還原設定。對於 ONTAP tools for VMware vSphere 10.3 及更早版本，請使用零 RPO 來還原設定。在受保護的環境中還原後，請重新驗證資料存放區保護，並確認保護群組的狀態和關係。


====
.開始之前
* 升級前請確保所有節點均已啟動。
* 確保ONTAP系統憑證和已加入的 vCenter 憑證有效期限至少為 5 天。如果憑證提前過期，升級將失敗。
* 確保所有節點上都有第五個磁碟，容量為 100 GB。
* 驗證節點配置是否符合下表中的規格。


|===
| 部署類型 | 每個節點的 CPU 核心數 | 每個節點的記憶體（GB） | 每個節點的磁碟空間（GB） | CPU 核心總數 | 總記憶體容量（GB） | 總磁碟空間（GB） 


| 非 HA 小型 | 9 | 18 | 350 | 9 | 18 | 350 


| 非 HA 中型 | 13 | 26 | 350 | 13 | 26 | 350 


| HA Small | 9 | 18 | 350 | 27 | 54 | 1050 


| HA 中型 | 13 | 26 | 350 | 39 | 78 | 1050 


| HA 大型 | 17 | 34 | 350 | 51 | 102. | 1050 
|===
* 啟用低 RPO 備份，並確保在 vSphere Client 介面中可見一個備份。升級前請下載備份資料夾。
* 建議採用低 RPO 備份。但是，在非高可用性部署中，您可以在升級之前對ONTAP工具虛擬機器進行靜默快照。
+
請參閱 link:../manage/backup-settings.html["編輯備份設定"] 和 link:../manage/recover-backup.html["恢復ONTAP工具設定"] 有關備份和復原的更多資訊。



.步驟
. 將適用於 VMware vSphere 的 ONTAP 工具升級 ISO 上傳至內容庫。
. 在主 VM 頁面中，選擇「操作」>「編輯設定」。若要確定主虛擬機器名稱：
+
.. 在任意節點上啟用診斷 shell
.. 運行以下命令：
`grep sourceHost /opt/netapp/meta/ansible_vars.yaml`


. 在編輯設定視窗中的*CD/DVD 磁碟機*欄位下選擇*內容庫 ISO 檔案*。
. 選擇 ISO 文件，選取 *CD/DVD 磁碟機* 欄位的 *已連接* 框，然後按一下 *確定*。
. 登入 vCenter 伺服器。
. 找到主要 ONTAP tools VM 並啟動 Web 主控台。
. 請使用 `maint`憑證登入。
. 輸入*2*選擇*系統配置*選單。
. 輸入 *6* 以選擇 *升級* 選項。
. 當系統提示時，請提供 vCenter 認證。這是託管 ONTAP tools 的 vCenter 實例。
+
如果您在雙 vCenter Server 拓撲中使用 ONTAP 工具（其中應用裝置託管在一個 vCenter 執行個體中並管理另一個執行個體），則可以為託管 ONTAP 工具的 vCenter 執行個體指派受限角色。您可以建立專用的 vCenter 使用者和角色，僅授予部署 OVF 範本所需的權限。如需詳細資訊，請參閱 link:../concepts/rbac-vcenter-use.html#vsphere-object-hierarchy["適用於 VMware vSphere 10 的 ONTAP 工具隨附的角色"] 中列出的角色。

+
對於將由ONTAP工具管理的 vCenter 實例，請確保 vCenter 使用者帳戶具有管理員權限。

+
在升級過程中，如果任何內建儲存後端憑證缺少主題備用名稱 (SAN) 項目，您將收到提示，指出缺少 SAN。如果您選擇在未驗證 SAN 的情況下繼續，升級將繼續，但由於潛在的安全風險，因此不建議這樣做。

. 升級時、系統會自動執行下列動作：
+
.. 閘道憑證已續期，有效期限為 1 年。當您移除先前的 SRA 介面卡並上傳新的 10.6 介面卡時，SRA 憑證的有效期將從 10 年變為 1 年。
.. 遠端插件已升級
.. ONTAP和 vCenter Server 憑證經過驗證並新增至ONTAP工具中
.. 已啟用備份
.. 如果主機叢集保護設定存在於 10.5 或更早版本中，ONTAP tools 會在升級期間建立一個分隔的 *Cluster protection configuration* 導覽項目。




.下一步
升級至 ONTAP tools for VMware vSphere 10.6 之後：

* 監控系統警報並計劃在一年內網關證書到期之前更新它。
* 移除 ONTAP tools 10.4 或 10.5 SRA 介面卡，並上傳 10.6 SRA 介面卡 tar 檔案。
* 上傳 SRA 適配器 tar 檔案後，執行安裝指令。然後，重新掃描 SRA 適配器以更新 VMware Site Recovery Storage Replication Adapters 頁面。
* 開啟 *Cluster protection configuration*，並驗證現有主機叢集保護設定是否存在且映射正確。


升級後您可以：

* 透過 ONTAP tools Manager 停用服務
* 從非 HA 設定移至 HA 設定
* 將非 HA 小型配置擴展為非 HA 中型配置，或擴展為 HA 中型或大型配置。


.相關資訊
link:../migrate/migrate-to-latest-ontaptools.html["將 ONTAP tools for VMware vSphere 9.x 移轉至 10.6"]
