---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: VASA Provider migration, SRA update, VMware Live Site Recovery, ONTAP tools migration, vVols migration, migration jobs, Swagger, REST API 
summary: 將 VASA Provider 移轉並將 SRA 從 ONTAP tools 9.x 更新至 10.6，以支援 VMware Live Site Recovery。 
---
= 遷移 VASA Provider 並在 ONTAP tools 中更新 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用此工作將 VASA Provider 從 ONTAP tools for VMware vSphere 9.xx 移轉至 10.6，並更新 VMware Live Site Recovery 應用裝置上的 Storage Replication Adapter （SRA）。



[[migrate-the-vasa-provider]]
== 遷移 VASA 提供程序

.開始之前
確保已部署 ONTAP tools for VMware vSphere 10.6，且目標 vCenter Server 和儲存設備後端已準備好進行移轉。

. 若要在現有的 ONTAP tools for VMware vSphere 應用裝置上啟用 Derby 連接埠 1527，請啟用 root 使用者，透過 SSH 登入 CLI，然後執行下列命令：
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. 為 VMware vSphere 10.6 部署 ONTAP tools for VMware vSphere 的 OVA。
. 新增您要移轉至 ONTAP tools for VMware vSphere 10.6 的 vCenter Server 執行個體。請參閱 link:../configure/add-vcenter.html["新增 vCenter Server 執行個體"] 以取得詳細資訊。
. 透過 vCenter Server API，在本機為 ONTAP tools 外掛上線儲存設備後端。如需詳細資訊，請參閱 link:../configure/add-storage-backend.html["使用 vSphere Client 介面新增儲存設備後端"]。
. 取得存取權杖以驗證 REST API 請求。請使用以下範例，並將變數替換為特定於您環境的值。
+
[source, curl]
----
curl --request POST \
  --location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/vcenter-login" \
  --header "Content-Type: application/json" \
  --header "Accept: */*" \
  -d '{"username": "$MYUSER", "password": "$MYPASSWORD", "vcenter hostname": "$MYVCENTER"}'
----
+
複製並保存回應中傳回的存取令牌。

. 從 Swagger 或 Postman 發出以下移轉 API 呼叫。
+
[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+
您可以透過此 URL 存取 Swagger： `\https://$FQDN_IP_PORT/` ， 例如： `\https://10.67.25.33:8443/` 。

+
[]
====
* HTTP 方法和端點 *

此 REST API 呼叫使用下列方法和端點。

|===


| * HTTP方法* | *路徑* 


| 貼文 | /API/v1 
|===
* 處理類型 *

非同步

* 目前範例 *

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
  --header 'x-auth: <auth_token>' \
  --header 'Content-Type: application/json' \
  --data '{
    "otv_ip": "xx.xx.xx.xx",
    "vasa_provider_credentials": {
      "username": "xxxxx",
      "password": "******"
    },
    "database_password": "******"
  }'
----
其他版本移轉的要求本文：

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
* JSON 輸出範例 *

系統傳回一個作業對象。儲存作業標識符以便在下一個步驟中使用。

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====




[[check-migration-status]]
=== 檢查移轉狀態

. 使用 Swagger 中的下列 URI 檢查狀態：
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobId>?includeSubJobsAndTasks=true`
----
+
使用上一步遷移作業傳回的「id」值。作業完成後，請檢閱作業回應中的遷移報告。





[[register-and-verify-the-migrated-vasa-provider]]
=== 註冊並驗證已移轉的 VASA 供應商

. 使用ONTAP tools for VMware vSphere 的VASA 提供者。有關說明，請參閱link:../configure/registration-process.html["註冊 VASA Provider"]。
. 驗證 VASA Provider 註冊：
+
.. 在 vSphere Client 中，導覽至 vCenter Server 。
.. 選擇 *Configure* > *Storage Providers* 。
.. 確認上一步驟中註冊的 VASA Provider 顯示為線上。


. 請依照下列步驟停止ONTAP tools for VMware vSphere：
+
.. 在ONTAP工具 9.x 中，開啟 Web 控制台。
.. 請使用 `maint`憑證登入。
.. 進入 `1`選擇“應用程式配置”選單。
.. 進入 `5`停止 VASA Provider 和 SRA 服務。
.. 在 vSphere Client 中，導航至 vCenter Server 並選擇 *Configure* > *Storage Providers*。
.. 選擇 ONTAP 工具 9.x 的離線 VASA Provider，然後選擇 *Remove*。
+
舊的 VASA 供應商停止後，vCenter 伺服器將容錯移轉至 ONTAP tools for VMware vSphere。所有資料存放區和 VM 均可存取，並由 ONTAP tools for VMware vSphere 提供服務。



. 移轉後的 NFS 和 VMFS 資料存放區會在資料存放區探索工作完成後出現在 ONTAP tools for VMware vSphere 10.6 中，該工作可能需要長達 30 分鐘。請在總覽頁面上查看其可見度。




[[run-the-patch-migration]]
=== 執行修補程式移轉

. 使用 Swagger 或 Postman 執行修補程式移轉 API 呼叫：
+
[]
====
* HTTP 方法和端點 *

此 REST API 呼叫使用下列方法和端點。

|===


| * HTTP方法* | *路徑* 


| 修補程式 | /API/v1 
|===
* 處理類型 *

非同步

請在 Swagger 中使用以下 URI：

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
* HTTP 方法和端點 *

此 REST API 呼叫使用下列方法和端點。

|===


| * HTTP方法* | *路徑* 


| 修補程式 | /API/v1 
|===
* 處理類型 *

非同步

請在 Swagger 中使用以下 URI：

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
* 目前範例 *

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
* JSON 輸出範例 *

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+

NOTE: 在 PATCH API 呼叫中使用步驟 7 中傳回的「migration_id」值作為 <migration_id>。PATCH 操作的請求體為空。

+

NOTE: UUID 是移轉後 API 所傳回的移轉 UUID 。



執行修補程式移轉 API 之後，所有 VM 都會遵守儲存原則。



[[after-migration]]
== 移轉後

完成移轉並將 ONTAP tools 10.6 註冊到 vCenter Server 後，請依照下列步驟操作：

* 等待*發現*完成，系統會自動在所有主機上刷新憑證。
* 等待資料儲存區和虛擬機器操作開始。等待時間取決於主機、資料儲存和虛擬機器的數量。如果您不等待，您可能會偶爾看到失敗。


升級後，如果虛擬機器的規範狀態已過期，請使用下列步驟重新套用儲存原則：

. 前往資料儲存並選擇*摘要*>*虛擬機器儲存策略*。
. 系統顯示*虛擬機器儲存策略合規性*下的合規性狀態為*過時*。
. 選擇儲存虛擬機器策略和對應的虛擬機器。
. 選擇*應用*。
. *虛擬機器儲存策略合規性*下的合規性狀態顯示為合規性。


.相關資訊
* link:../concepts/rbac-learn-about.html["瞭解適用於 VMware vSphere 10 RBAC 的 ONTAP 工具"]
* link:../upgrade/upgrade-ontap-tools.html["將 ONTAP tools for VMware vSphere 10.x 升級至 10.6"]




[[update-the-storage-replication-adapter-sra]]
== 更新儲存設備複寫介面卡 （SRA）

.開始之前
在移轉 SRA 之前，請先驗證以下內容：

* 在恢復計畫中，受保護站點是虛擬機器目前運作的位置，而恢復站點是虛擬機器將恢復的位置。
* 在 VMware Live Site Recovery 應用裝置介面中，一個站點顯示為受保護狀態，另一個站點顯示為恢復狀態。
* 在恢復計畫中，*CLEANUP* 和 *REPROTECT* 按鈕已停用，*TEST* 和 *RUN* 按鈕仍保持啟用。



NOTE: 如果容錯移轉已完成但重新保護仍在擱置中，請勿開始移轉。請確保重新保護程序完成後再繼續進行移轉。如果測試容錯移轉正在進行中，請清除測試容錯移轉並開始移轉。

. 請依照下列步驟，在 VMware 網站恢復中刪除適用於 VMware vSphere 9.xx 的工具 ONTAP 介面卡：
. 前往 VMware Live Site Recovery 組態管理頁面。
+
.. 移至 * 儲存複寫介面卡 * 區段。
.. 從省略符號功能表中選取 * 重設組態 * 。
.. 從省略符號功能表中選取 * 刪除 * 。


. 在保護站點和恢復站點上執行這些步驟。
+
.. link:../manage/enable-services.html["為 VMware vSphere 服務啟用 ONTAP 工具"]
.. 請依照 link:../protect/configure-on-srm-appliance.html["在 VMware Live Site Recovery 應用裝置上設定 SRA"] 中的步驟設定 ONTAP tools for VMware vSphere 10.6 SRA 介面卡。
.. 在 VMware Live Site Recovery 介面上，運行 *Discover Arrays* 和 *Discover Devices*。確認設備顯示與遷移前相同。



