---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: 移轉儲存資料時、會使用 REST API 手動建立儲存後端。移轉 VASA Provider 資料時，資料會從現有的 Derby 資料庫匯出，並匯入至 MongoDB 資料庫。 
---
= 遷移 VASA 提供者並更新 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== 遷移 VASA 提供者的步驟

. 若要在現有的 ONTAP 工具上啟用 VMware vSphere 的 Derby 連接埠 1527 ，請啟用 root 使用者，並透過 SSH 登入 CLI 。然後執行下列命令：
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. ONTAP tools for VMware vSphere的 OVA。
. 新增要移轉到ONTAP tools for VMware vSphere的 vCenter Server 執行個體。請參閱link:../configure/add-vcenter.html["新增 vCenter Server 執行個體"]了解更多。
. 透過 vCenter 伺服器 API 在本地為 ONTAP 工具插件加入儲存後端。
. 從 Swagger 或 Postman 發出下列 API 以進行移轉。
+
curl -X POST  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`

+
您可以透過此 URL 存取 Swagger： `\https://$FQDN_IP_PORT/` ， 例如： `\https://10.67.25.33:8443/` 。

+
[]
====
* HTTP 方法和端點 *

此 REST API 呼叫使用下列方法和端點。

|===


| * HTTP方法* | *路徑* 


| 貼文 | /API/v1 
|===
* 處理類型 *

非同步

* 目前範例 *

curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs'[] \ --header 'x-auth：<auth_token>' \ --header 'Content-Type：application/json' \ --data '{“otv_ip”：“xx.xx.xx.xx”，“vasa_provider_credentials”：{“用戶名”：“xxxxx”，“密碼”：“x*”，“用戶名”

其他版本移轉的要求本文：

{ “otv_ip”：“xx.xx.xx.xx”， “vasa_provider_credentials”：{ “用戶名”：“xxxxx”，“密碼”：“*******” } }

* JSON 輸出範例 *

工作物件即會傳回。您應該儲存工作識別碼、以便在下一步中使用。

｛
  「 ID 」： 123 、
  " 移轉識別碼 " ： "d50073ce-35b4-4c51-9d2e-4ce66f802c35" 、
  " 狀態 " ： " 執行中 "
}

====
. 使用 Swagger 中的下列 URI 檢查狀態：
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
完成工作後，請檢閱移轉報告。此報告包含在工作資料中，可從工作回應存取。

. 將適用於 VMware vSphere 儲存提供者的 ONTAP 工具新增至 vCenter Server 並link:../configure/registration-process.html["註冊 VASA Provider"]使用適用於 VMware vSphere 的 ONTAP 工具。
. link:../manage/enable-services.html["啟用 VASA Provider"]ONTAP tools for VMware vSphere上的服務。
. 從維護主控台停止適用於 VMware vSphere 儲存供應商 9.10/9.11/9.12/9.13 VASA Provider 服務的 ONTAP 工具。
+
不要刪除 VASA 提供者。

+
舊 VASA 提供者停止後，vCenter Server 將故障轉移到ONTAP tools for VMware vSphere。所有資料儲存庫和虛擬機器均可訪問，並由適用於ONTAP tools for VMware vSphere提供服務。

. 只有在觸發資料儲存發現作業後，從ONTAP tools for VMware vSphere遷移的 NFS 和 VMFS 資料儲存才會在ONTAP tools for VMware vSphere中可見，這可能需要長達 30 分鐘才能完成。驗證資料儲存庫是否在 VMware vSphere 外掛程式使用者介面頁面的ONTAP工具概覽頁面上可見。
. 使用 Swagger 或 Postman 中的下列 API 執行修補程式移轉：
+
[]
====
* HTTP 方法和端點 *

此 REST API 呼叫使用下列方法和端點。

|===


| * HTTP方法* | *路徑* 


| 修補程式 | /API/v1 
|===
* 處理類型 *

非同步

* 目前範例 *

curl -X 補丁 `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43`

* JSON 輸出範例 *

工作物件即會傳回。您應該儲存工作識別碼、以便在下一步中使用。

｛
  「 ID 」： 123 、
  " 移轉識別碼 " ： "d50073ce-35b4-4c51-9d2e-4ce66f802c35" 、
  " 狀態 " ： " 執行中 "
}

要求主體是空的，用於修補作業。


NOTE: UUID 是移轉後 API 所傳回的移轉 UUID 。

執行修補程式移轉 API 之後，所有 VM 都會遵守儲存原則。

====


.下一步
完成遷移並將ONTAP Tools 10.5 註冊到 vCenter Server 後，請依照下列步驟操作：

* 等待 * 探索 * 完成，所有主機上的憑證都會自動重新整理。
* 啟動資料儲存區和虛擬機器操作之前，請留出足夠的時間。所需的等待時間會因配置中的主機、資料儲存區和虛擬機器的數量而異。等待失敗可能會導致間歇性操作失敗。


升級後，如果虛擬機器的規範狀態已過期，請使用下列步驟重新套用儲存原則：

. 前往資料儲存並選擇*摘要*>*虛擬機器儲存策略*。
+
在 * VM 儲存原則相容性 * 下的法規遵循狀態顯示為 * 過時 * 。

. 選取儲存 VM 原則和對應的 VM
. 選取 * 套用 *
+
在 * VM 儲存原則相容性 * 下的法規遵循狀態現在顯示為相容。



.相關資訊
* link:../concepts/rbac-learn-about.html["瞭解適用於 VMware vSphere 10 RBAC 的 ONTAP 工具"]
* link:../upgrade/upgrade-ontap-tools.html["將適用於ONTAP tools for VMware vSphere升級至 10.5"]




== 更新儲存複製適配器 (SRA) 的步驟

.開始之前
在復原計畫中，受保護站點是指虛擬機器目前運作的位置，而復原站點是指虛擬機器將被復原的位置。 SRMVMware Live Site Recovery 設備介面顯示復原計畫的狀態，包括受保護網站和復原站點的詳細資訊。在復原計畫中，CLEANUP 和 REPROTECT 按鈕被停用，而 TEST 和 RUN 按鈕仍然啟用。這表示該站點已準備好進行資料恢復。在遷移 SRA 之前，請先驗證一個網站處於受保護狀態，另一個網站處於復原狀態。


NOTE: 如果故障轉移已完成但重新保護仍處於待定狀態，則不要開始遷移。確保在繼續遷移之前重新保護過程已完成。如果正在進行測試故障轉移，請清理測試故障轉移並開始遷移。

. 請依照下列步驟，在 VMware 網站恢復中刪除適用於 VMware vSphere 9.xx 的工具 ONTAP 介面卡：
+
.. 前往 VMware Live Site Recovery 組態管理頁面
.. 移至 * 儲存複寫介面卡 * 區段。
.. 從省略符號功能表中選取 * 重設組態 * 。
.. 從省略符號功能表中選取 * 刪除 * 。


. 在保護站點和恢復站點上執行這些步驟。
+
.. link:../manage/enable-services.html["為 VMware vSphere 服務啟用 ONTAP 工具"]
.. 使用下列步驟ONTAP tools for VMware vSpherelink:../protect/configure-on-srm-appliance.html["在 VMware Live Site Recovery 應用裝置上設定 SRA"]。
.. 在 VMware Live Site Recovery 使用者介面頁面上，執行 * 探索陣列 * 和 * 探索裝置 * 作業，並確認裝置在移轉之前顯示為。



