---
permalink: deploy/ha-three-node-deployment.html 
sidebar: sidebar 
keywords:  
summary: 您可以在小型、中型或大型組態中設定 HA 。 
---
= 部署 HA 組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在小型、中型或大型組態中設定 HA 三個節點。HA 部署使用 Trident 來儲存服務資料。

* 小型 HA 三個節點每個節點包含 8 個 CPU 和 16 GB RAM 。
* 中高可用度三個節點每個節點包含 12 個 CPU 和 24 GB RAM 。
* 大型 HA 三個節點每個節點包含 16 個 CPU 和 32 GB RAM 。


*開始之前*

本工作提供如何在小型、中型或高組態中安裝 HA 三個節點的說明。


NOTE: 建立內容庫是部署 HA 三個節點組態的必要步驟。請參閱link:../deploy/download-ontap-tools.html["建立內容庫"]一節以瞭解程序。如需詳細資訊、請參閱 https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["建立及使用內容庫"]部落格。

請確定您已將 OVA 匯入內容庫。請將內容庫的名稱和您提供給 OVA 項目的文件庫項目名稱保留在手邊。


NOTE: 在繼續部署之前、請在安裝 ONTAP 工具期間、將資源清冊上的叢集分散式資源排程器（ DRS ）設定為「保守」。如此可確保 VM 在安裝期間不會移轉。

*步驟*

. 登入 vSphere 伺服器。
. 瀏覽至您建立的資源集區、叢集或您要部署 OVA 的主機。
. 以滑鼠右鍵按一下所需位置、然後選取 * 部署 OVF 範本 ...* 。
+

NOTE: 請勿將適用於 VMware vSphere 虛擬機器的 ONTAP 工具部署在其管理的 VVols 資料存放區上。

. 透過 .ova_ 檔案的 URL 選取 OVA 檔案、或瀏覽至儲存 _.ova_ 檔案的資料夾、然後按一下 * 下一步 * 。
. 若要從內容庫部署適用於 VMware vSphere 的 ONTAP 工具：
+
.. 移至內容庫、然後按一下您要部署的文件庫項目。
.. 按一下 * 動作 * > * 此範本的新 VM *


. 選取電腦資源、然後按一下 * 下一步 * 。
. 檢閱範本的詳細資料、然後按一下 * 下一步 * 。
. 閱讀並接受授權合約、然後按一下 * 下一步 * 。
. 選擇部署組態、然後按一下 * 下一步 * 。
. 選擇用於配置和磁盤文件的存儲設備，然後單擊 *Next* （下一步 * ）。
. 選擇每個來源網路的目的地網路、然後按一下 * 下一步 * 。
. 在 * 自訂範本 * 視窗中、填寫必填欄位、然後按一下 * 下一步 * 。
+
** 啟用 SVM 範圍時、您應該已啟用 SVM 支援、並提供管理 IP 位址。
** 此處提供的資訊在安裝過程中已通過適當模式的驗證。若有差異、網路主控台會顯示錯誤訊息、並提示您更正所提供的任何不正確資訊。
** 主機名稱必須包含大寫字母（ A-Z ）、小寫字母（ a-z ）、數字（ 0-9 ）或連字號（ - ）特殊字元。如果您要設定雙堆疊、請指定對應至 IPv6 位址的主機名稱。


. 查看 * 準備完成 * 視窗中的詳細資料、選取 * 完成 * 。
+
在建立部署工作時、進度會顯示在 vSphere 工作列中。

. 在工作完成後開啟虛擬機器電源。
+
安裝隨即開始。您可以在 VM 的 Web 主控台中追蹤安裝進度。在安裝過程中、會驗證節點組態。在 OVF 表單的自訂範本下的不同區段下提供的輸入都會經過驗證。若有任何差異、對話方塊會提示您採取修正行動。

. 在對話方塊提示中進行必要的變更。使用 Tab 鍵瀏覽面板、然後選取 * 確定 * 。
+
提供的值將再次驗證。VMware vSphere 的 ONTAP 工具可讓您嘗試三次修正任何無效值。如果三次嘗試後仍無法修正問題、產品安裝將會停止、建議您嘗試在新的 VM 上安裝。



安裝成功之後、 Web 主控台會顯示 VMware vSphere 的 ONTAP 工具狀態。
