---
permalink: deploy/nonha-deployment.html 
sidebar: sidebar 
keywords:  
summary: 您可以在中小型組態中設定非 HA 單一節點。 
---
= 部署非 HA 單節點組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在中小型組態中部署非 HA 單節點組態。

* 小型非 HA 組態包含 8 個 CPU 和 16 GB RAM 。
* 中型非 HA 組態包含 12 個 CPU 和 24 GB RAM 。


*開始之前*

確定網路路由存在。儲存資料網路必須可從 VM 管理網路存取。例如、登入 ONTAP > 執行命令 _network route create -vserver <SVM> -destination 0.0.0.0/0 -gateway <gateway_ip> _

*步驟*

. 登入 vSphere 伺服器。
. 瀏覽至您建立的資源集區、叢集或您要部署 OVA 的主機。
. 以滑鼠右鍵按一下所需位置、然後選取 * 部署 OVF 範本 ...* 。
+

NOTE: 請勿將適用於 VMware vSphere 虛擬機器的 ONTAP 工具部署在其管理的 VVols 資料存放區上。

. 透過 .ova_ 檔案的 URL 選取 OVA 檔案、或瀏覽至儲存 _.ova_ 檔案的資料夾、然後按一下 * 下一步 * 。
. 選取電腦資源、然後按一下 * 下一步 * 。
. 檢閱範本的詳細資料、然後按一下 * 下一步 * 。
. 閱讀並接受授權合約。
. 選擇部署組態、然後按一下 * 下一步 * 。
+
進階部署選項使用 Trident 做為 ONTAP 的動態儲存資源配置程式來建立磁碟區、而簡易部署則使用本機儲存設備來建立磁碟區。

. 選擇用於配置和磁盤文件的存儲設備，然後單擊 *Next* （下一步 * ）。
. 選擇每個來源網路的目的地網路、然後按一下 * 下一步 * 。
. 在 * 自訂範本 * 中、輸入必要的詳細資料、然後按一下 * 下一步 *
+
** 啟用 SVM 範圍時、您應該已啟用 SVM 支援、並提供管理 IP 位址。
** 此處提供的資訊在安裝過程中已通過適當模式的驗證。若有差異、網路主控台會顯示錯誤訊息、並提示您更正所提供的任何不正確資訊。
** 主機名稱必須包含大寫字母（ A-Z ）、小寫字母（ a-z ）、數字（ 0-9 ）或連字號（ - ）特殊字元。如果您要設定雙堆疊、請指定對應至 IPv6 位址的主機名稱。


. 查看 * 準備完成 * 視窗中的詳細資料、選取 * 完成 * 。
+
在建立部署工作時、進度會顯示在 vSphere 工作列中。

. 在工作完成後開啟虛擬機器電源。
+
安裝隨即開始。您可以在 VM 的 Web 主控台中追蹤安裝進度。在安裝過程中、會驗證節點組態。在 OVF 表單的自訂範本下的不同區段下提供的輸入都會經過驗證。若有任何差異、對話方塊會提示您採取修正行動。

. 在對話方塊提示中進行必要的變更。使用 Tab 鍵瀏覽面板、然後選取 * 確定 * 。
+
提供的值將再次驗證。VMware vSphere 的 ONTAP 工具可讓您嘗試三次修正任何無效值。如果三次嘗試後仍無法修正問題、產品安裝將會停止、建議您嘗試在新的 VM 上安裝。



安裝成功之後、 Web 主控台會顯示 VMware vSphere 的 ONTAP 工具狀態。
