---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: 適用於 VMware vSphere 應用程式的 ONTAP 工具一律部署為小型單一節點，並提供核心服務以支援 NFS/VMFS 資料存放區。 
---
= 部署適用於 VMware vSphere 的 ONTAP 工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於 VMware vSphere 應用程式的 ONTAP 工具一律部署為小型單一節點，並提供核心服務以支援 NFS/VMFS 資料存放區。

*開始之前*

VMware 中的內容庫是儲存 VM 範本、 vApp 範本及其他類型檔案的容器物件。使用內容庫進行部署可提供無縫體驗、因為它並不受網路連線能力的限制。


NOTE: 您應該將內容庫儲存在共享的資料存放區、這樣叢集中的所有主機都可以存取它。您必須先建立內容庫以儲存 OVA ，然後再將應用裝置設定變更為 HA 組態。內容庫範本一旦上傳，就不應在部署後刪除。


NOTE: 若要稍後啟用 HA 部署，則不應將裝載 ONTAP 工具的虛擬機器直接部署在 ESXi 主機上。而是應將其部署在叢集或資源集區上。

如果您還沒有合適的內容庫，請使用下列步驟建立：


NOTE: 如果您只打算使用小型單一節點部署，則不需要建立內容庫。

.  `.zip`從下載包含適用於 VMware vSphere 的 ONTAP 工具二進位檔案（ _.ova_ ）和簽署憑證 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp 支援網站"^]的檔案。
. 使用登入 vSphere 用戶端 `\https://<vcenterip>/<ui>`
. 選取 vSphere 用戶端旁的水平省略號、然後選取 * 內容庫 * 。
. 選取頁面右側的 * 建立 * 。
. 提供文件庫名稱並建立內容庫。
. 瀏覽至您建立的內容庫。
. 選取頁面右側的 * 動作 * 、然後選取 * 匯入項目 * 並匯入 OVA 檔案。



NOTE: 如需詳細資訊、請參閱 https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["建立及使用內容庫"]部落格。

請確定您已將 OVA 匯入內容庫。


NOTE: 在繼續部署之前、請在安裝 ONTAP 工具期間、將資源清冊上的叢集分散式資源排程器（ DRS ）設定為「保守」。如此可確保 VM 在安裝期間不會移轉。

.步驟
.  `.zip`從下載包含適用於 VMware vSphere 的 ONTAP 工具二進位檔案（ _.ova_ ）和簽署憑證 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp 支援網站"^]的檔案。如果您已將 OVA 匯入內容庫，您可以跳過此步驟並繼續下一步，因為您可以直接從內容庫部署。
. 登入 vSphere 伺服器。
. 瀏覽至您建立的資源集區、叢集或您要部署 OVA 的主機。
. 以滑鼠右鍵按一下所需位置、然後選取 * 部署 OVF 範本 ...* 。
+

NOTE: 切勿將適用於 VMware vSphere 虛擬機器的 ONTAP 工具儲存在他們所管理的 VVols 資料存放區上。

. 透過 .ova_ 檔案的 URL 選取 OVA 檔案，或瀏覽至儲存 _.ova_ 檔案的資料夾，然後選取 * 下一步 * 。
. 若要從內容庫部署適用於 VMware vSphere 的 ONTAP 工具：
+
.. 移至內容庫並選取您要部署的文件庫項目。
.. 選擇 * 操作 * > * 從此範本新增虛擬機器 *


. 在 * 選取虛擬機器的名稱和資料夾 * 視窗中，輸入虛擬機器名稱，然後選取虛擬機器的位置。如果勾選 * 自訂此虛擬機器的硬體 * 核取方塊，則會先啟用名為 * 自訂硬體 * 的步驟，然後再進入 * 準備完成 * 視窗。
. 選取電腦資源，然後選取 * 下一步 * 。您可以選擇核取「自動啟動已部署的 VM* 」核取方塊。
. 檢閱範本的詳細資料，然後選取 * 下一步 * 。
. 閱讀並接受授權合約、然後選擇 * 下一步 * 。
. 選取組態和磁碟檔案的儲存設備，然後選取 * 下一步 * 。
. 選取每個來源網路的目的地網路，然後選取 * 下一步 * 。
. 在 * 自訂範本 * 視窗中，填寫必填欄位，然後選取 * 下一步 * 。
+
** 此處提供的資訊在安裝過程中已通過適當模式的驗證。若有差異、網路主控台會顯示錯誤訊息、並提示您更正所提供的任何不正確資訊。
** 主機名稱必須包含大寫字母（ A-Z ）、小寫字母（ a-z ）、數字（ 0-9 ）或連字號（ - ）特殊字元。如果您要設定雙堆疊、請指定對應至 IPv6 位址的主機名稱。
+

NOTE: 不支援 Pure IPv6 。同時具有 IPv6 和 IPv4 位址的 VLAN 支援混合模式。



. 在 * 自訂硬體 * 視窗中，您應該啟用 CPU 熱新增和記憶體熱插拔。
. 查看 * 準備完成 * 視窗中的詳細資料、選取 * 完成 * 。
+
在建立部署工作時、進度會顯示在 vSphere 工作列中。

. 在工作完成後開啟虛擬機器電源。
+

NOTE: 在開機之前，請確定 VM 已啟用 CPU 和記憶體的熱插件。



您可以在 VM 的 Web 主控台中追蹤安裝進度。

如果 OVF 表單中輸入的值有任何差異、則會出現對話方塊提示您採取修正行動。在對話方塊中進行必要的變更、使用 Tab 鍵瀏覽並選取「確定」。您有三次嘗試來修正任何問題。如果三次嘗試後問題持續發生，安裝程序將會停止，建議您在新的 VM 上重試安裝。
