---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 您應該建立保護群組、以保護受保護站台上的一組虛擬機器。 
---
= 設定受保護和恢復站台
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該建立保護群組、以保護受保護站台上的一組虛擬機器。

當您新增的資料儲存區時，您可以將其新增至現有的資料儲存區群組中，也可以新增新的資料儲存區並建立新的磁碟區或一致性群組以進行保護。將新的資料儲存區新增至受保護的一致性群組或磁碟區後，更新SnapMirror並在受保護網站和復原網站上執行儲存發現。您可以手動或按計劃執行發現，以確保偵測到並保護新的資料儲存區。



== 配對受保護和恢復站台

您應該配對使用 vSphere Client 建立的受保護網站和還原網站、以啟用 Storage Replication Adapter （ SRA ）來探索儲存系統。


NOTE: 儲存複製適配器 (SRA) 支援具有自動故障轉移雙工類型的一個同步關係的扇出以及一致性群組上的非同步關係 SnapMirror。但是，不支援在一致性群組上使用兩個非同步 SnapMirror 的開機，或在 Volume 上使用扇出 Snapscorors 。

.開始之前
* 您應該在受保護的網站和還原網站上安裝 VMware Live Site Recovery 。
* 您應該在受保護的網站和還原網站上安裝 SRA 。


.步驟
. 按兩下 vSphere Client 首頁上的 * 站台恢復 * ，然後選取 * 站台 * 。
. 選取 * 物件 * > * 動作 * > * 配對站台 * 。
. 在 * 配對 Site Recovery Manager Servers* 對話方塊中，輸入受保護站台平台服務控制器的位址，然後選取 * 下一步 * 。
. 在「選取vCenter Server」區段中、執行下列動作：
+
.. 確認受保護站台的vCenter Server顯示為配對的相符候選對象。
.. 輸入 SSO 管理認證，然後選取 * 完成 * 。


. 如果出現提示，請選取 * 是 * 以接受安全性憑證。


.結果
受保護和還原站台都會顯示在「物件」對話方塊中。



== 設定保護群組

.開始之前
您應確保來源站台和目標站台均設定為下列項目：

* 安裝的 VMware Live Site Recovery 版本相同
* 虛擬機器
* 配對的受保護與恢復站台
* 來源與目的地資料存放區應掛載於個別站台


.步驟
. 登入 vCenter Server 並選擇“Site Recovery”>“Protection Groups”。
. 在 * 保護群組 * 窗格中，選取 * 新 * 。
. 指定保護群組，方向的名稱和說明，然後選取 * 下一步 * 。
. 在「類型」欄位中，選擇「資料儲存組（基於陣列的複製）」作為 NFS 和 VMFS 資料儲存區的「類型」欄位選項...*。故障域僅包含已啟用複製的 SVM。系統會顯示僅實施了對等連線且沒有問題的 SVM。
. 在 [ 複寫群組 ] 索引標籤中，選取已啟用的陣列配對或已設定虛擬機器的複寫群組，然後選取 [ 下一步 ] 。
+
複寫群組上的所有虛擬機器都會新增至保護群組。

. 您可以選擇現有的復原計劃，也可以透過選擇「新增至新復原計劃」來建立新的復原計劃。
. 在 [ 即將完成 ] 索引標籤中，檢閱您所建立保護群組的詳細資料，然後選取 [ 完成 ] 。

