---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 您應該建立保護群組、以保護受保護站台上的一組虛擬機器。 
---
= 在 ONTAP tools 中設定受保護站台和復原站台
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該建立保護群組、以保護受保護站台上的一組虛擬機器。

當您新增的資料儲存區時，您可以將其新增至現有的資料儲存區群組中，也可以新增新的資料儲存區並建立新的磁碟區或一致性群組以進行保護。將新的資料儲存區新增至受保護的一致性群組或磁碟區後，更新SnapMirror並在受保護網站和復原網站上執行儲存發現。您可以手動或按計劃執行發現，以確保偵測到並保護新的資料儲存區。



== 配對受保護和恢復站台

您應該配對使用 vSphere Client 建立的受保護網站和還原網站、以啟用 Storage Replication Adapter （ SRA ）來探索儲存系統。


NOTE: Storage Replication Adapter（SRA）支援扇出，其中一種同步關係類型為 Automated Failover Duplex，另一種為一致性群組上的非同步 SnapMirror 關係。但是，不支援在一致性群組上建立兩種非同步 SnapMirror 關係的扇出，也不支援在磁碟區上建立扇出 SnapMirror 關係。Vault 類型的 SnapMirror 關係不包含在這些扇出限制中。SRA 對一致性群組的支援僅限於 Unified 和 ASA r2 儲存系統上的 SAN 協定（iSCSI 和光纖通道）。一致性群組不支援 NFS。如果將 NFS 資料儲存磁碟區置於一致性群組下，則探索裝置操作將會失敗。

.開始之前
* 您應該在受保護的網站和還原網站上安裝 VMware Live Site Recovery 。
* 您應該在受保護的網站和還原網站上安裝 SRA 。


.步驟
. 在 vSphere Client 主頁上，雙擊 *Site Recovery* 圖標，然後選擇 *Sites*。
. 選取 * 物件 * > * 動作 * > * 配對站台 * 。
. 在 * 配對 Site Recovery Manager Servers* 對話方塊中，輸入受保護站台平台服務控制器的位址，然後選取 * 下一步 * 。
. 在「選取vCenter Server」區段中、執行下列動作：
+
.. 確認受保護站台的vCenter Server顯示為配對的相符候選對象。
.. 輸入 SSO 管理認證，然後選取 * 完成 * 。


. 如果出現提示，請選取 * 是 * 以接受安全性憑證。


.結果
*物件*對話方塊顯示受保護網站和復原網站。



== 設定保護群組

.開始之前
您應確保來源站台和目標站台均設定為下列項目：

* 安裝的 VMware Live Site Recovery 版本相同
* 虛擬機器
* 配對的受保護與恢復站台
* 來源與目的地資料存放區應掛載於個別站台


.步驟
. 登入 vCenter Server 並選擇“Site Recovery”>“Protection Groups”。
. 在 * 保護群組 * 窗格中，選取 * 新 * 。
. 指定保護群組，方向的名稱和說明，然後選取 * 下一步 * 。
. 在 *Type* 欄位中，選擇 *Type field option...* 作為 NFS 和 VMFS 資料存放區的資料存放區群組（陣列型複寫）。故障網域包含已啟用複寫的 SVM。僅實作對等關係且沒有問題的 SVM 會顯示。
. 在 [ 複寫群組 ] 索引標籤中，選取已啟用的陣列配對或已設定虛擬機器的複寫群組，然後選取 [ 下一步 ] 。
+
複寫群組上的所有虛擬機器都會新增至保護群組。

. 您可以選擇現有的復原計劃，也可以透過選擇「新增至新復原計劃」來建立新的復原計劃。
. 在 [ 即將完成 ] 索引標籤中，檢閱您所建立保護群組的詳細資料，然後選取 [ 完成 ] 。

