---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 您應該先設定儲存系統、再執行 Storage Replication Adapter （ SRA ） for VMware Live Site Recovery 。 
---
= 在 ONTAP tools 中為 SAN 和 NAS 環境配置 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該先設定儲存系統、再執行 Storage Replication Adapter （ SRA ） for VMware Live Site Recovery 。



== 為 SAN 環境設定 SRA

.開始之前
您應該在受保護的站台和還原站台上安裝下列程式：

* VMware Live Site Recovery：VMware 站點提供了 VMware Live Site Recovery 的安裝文件。
+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["關於 VMware Live Site Recovery"]

* SRA：在 VMware Live Site Recovery 上安裝適配器。


.步驟
. 確認主ESXi主機已連線至受保護站台上主要儲存系統的LUN。
. 確認 LUN 位於具有的 igroup 中 `ostype` 選項在主儲存系統上設為 _VMware_ 。
. 驗證復原站點上的 ESXi 主機是否與儲存虛擬機器 (SVM) 具有適當的 iSCSI 和光纖通道連線。輔助站點 ESXi 主機應該能夠存取輔助站點存儲，主站點 ESXi 主機應該能夠存取主站點存儲。
+
您可以透過驗證 ESXi 主機是否已在 SVM 或上連接本機 LUN 來執行此動作 `iscsi show initiators` SVM 上的命令。
檢查 ESXi 主機中對應 LUN 的 LUN 存取權、以驗證 iSCSI 連線能力。





== 為 NAS 環境設定 SRA

.開始之前
您應該在受保護的站台和還原站台上安裝下列程式：

* VMware Live Site Recovery：您可以在 VMware 網站上找到 VMware Live Site Recovery 的安裝文件 - https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["關於 VMware Live Site Recovery"]
* SRA：在 VMware Live Site Recovery 和 SRA 伺服器上安裝適配器。


.步驟
. 確認受保護站台的資料存放區包含已向vCenter Server註冊的虛擬機器。
. 確認受保護站台的ESXi主機已從儲存虛擬機器（SVM）掛載NFS匯出磁碟區。
. 使用陣列管理器精靈將陣列新增至 VMware Live Site Recovery 時，請驗證「*NFS 位址*」欄位中指定的有效位址（例如，存在 NFS 匯出的 IP 位址或 FQDN）。請勿在「*NFS 位址*」欄位中使用 NFS 主機名稱。
. 使用 `ping` 在恢復站台上的每個 ESXi 主機上執行命令、以驗證主機是否有 VMkernel 連接埠、可存取用於從 SVM 匯出 NFS 的 IP 位址。

