---
permalink: protect/enable-storage-replication-adapter.html 
sidebar: sidebar 
keywords:  
summary: 適用於 VMware vSphere 的 ONTAP 工具可讓您選擇啟用 SRA 功能來設定災難恢復。 
---
= 在 ONTAP 工具中設定 SRA 以保護資料儲存區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於 VMware vSphere 的 ONTAP 工具可讓您選擇啟用 SRA 功能來設定災難恢復。

.開始之前
* 您應該已設定 vCenter Server 執行個體和已設定的 ESXi 主機。
* 您應該已部署適用於 VMware vSphere 的 ONTAP 工具。
* 您應該已 `.tar.gz`從下載過 SRA 介面卡檔案 https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab["NetApp 支援網站"^]。
* 在執行 SRA 工作流程之前，您應該在來源 ONTAP 叢集和目標ONTAP叢集上具有相同的自訂SnapMirror計畫。
* link:../manage/enable-services.html["為 VMware vSphere 服務啟用 ONTAP 工具"]啟用 SRA 功能。


.步驟
. 使用 URL ：登入 VMware Live Site Recovery 應用裝置管理介面 `\https://:<srm_ip>:5480`、然後前往 VMware Live Site Recovery 應用裝置管理介面中的 Storage Replication Adapters 。
. 選取 * 新介面卡 * 。
. 將適用於 SRA 外掛程式的 .tar.gz_ 安裝程式上傳至 VMware Live Site Recovery 。
. 重新掃描介面卡、確認「 VMware Live Site Recovery Storage Replication Adapters （ VMware Live Site Recovery 儲存複寫介面卡）」頁面上的詳細資料已更新。



NOTE: 故障轉移後，資料儲存區可能無法執行擴充、掛載和刪除等操作。執行資料儲存發現以刷新並顯示適當的上下文功能表操作。


NOTE: 每次重新保護操作後，您必須在兩個網站上執行儲存發現。

在具有 SRA 保護的新設定中，請始終執行測試故障轉移。跳過測試故障轉移可能會導致重新保護操作失敗。

在扇出配置中，在SnapMirror活動同步故障轉移（其中SnapMirror來源變更為網站 B 以進行自動故障轉移雙工和非同步SnapMirror）之後，在網站 B 和 C 之間執行測試故障轉移。跳過此步驟可能會導致重新保護操作失敗。

.相關資訊
https://docs.netapp.com/us-en/netapp-solutions-virtualization/vmware/vmw-nfs-vlsr.html#scenario-overview["使用 VMware Site Recovery Manager 設定 NFS 資料儲存區的災難復原"]
