---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: 若要讓 VMware Live Site Recovery 與 SRA 通訊、如果您已修改認證、則應更新 VMware Live Site Recovery 伺服器上的 SRA 認證。 
---
= 在 ONTAP tools 中更新 SRA 認證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要讓 VMware Live Site Recovery 與 SRA 通訊、如果您已修改認證、則應更新 VMware Live Site Recovery 伺服器上的 SRA 認證。

.開始之前
您應該已經執行了主題中提到的步驟 link:../protect/configure-on-srm-appliance.html["在 VMware Live Site Recovery 應用裝置上設定 SRA"]。

.步驟
. 執行以下命令、從 VMware Live Site Recovery 機器刪除快取的 ONTAP tools for VMware vSphere 認證資料：
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. 執行 Perl 命令、以新認證設定 SRA ：
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` 您需要針對密碼值提供單一報價。
+
系統會顯示成功訊息，確認儲存憑證已儲存。SRA 可以使用提供的 IP 位址、連接埠和憑證與 SRA 伺服器通訊。







== 憑證變更後，在 VMware Live Site Recovery 設備中重新配置 vCenter

如果 vCenter 憑證發生變更（例如 vCenter 升級後），您可能會在 Site Recovery 擴充功能中遇到指紋不符錯誤。請執行以下步驟解決此問題。

.步驟
. 在 VMware Live Site Recovery 設備中重新配置 vCenter
+
.. 在瀏覽器中開啟 VMware Live Site Recovery 應用裝置管理介面： `\https://<SRM_IP>:5480`
.. 選取 *Summary* 標籤。
.. 選取 *Reconfigure* 以重新設定 vCenter Server 連線。
+
這會從 vCenter 取得並接受最新的憑證指紋。



. 重新連接站台配對（如果錯誤仍然存在）
+
如果重新設定後指紋不符錯誤仍然存在：

+
.. 登入 vCenter 使用者介面。
.. 導覽至 *Site Recovery* 擴充功能。
.. 找到 *Site Pairing* 部分。
.. 選擇 *Reconnect* 以使用更新後的憑證重新建立網站配對。



