---
permalink: concepts/rbac-ontap-use.html 
sidebar: sidebar 
keywords: ONTAP RBAC deployment, custom roles, user configuration, JSON role definition 
summary: 在正式作業環境中使用 ONTAP tools 之前，請先審查 ONTAP RBAC 注意事項。 
---
= ONTAP tools for VMware vSphere 中的 ONTAP RBAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 透過 ONTAP 支援角色型存取控制 （RBAC），讓您能夠建立自訂使用者和角色，以限制對儲存資源的存取。瞭解組態程序和權限層級，有助於您在正式作業環境中部署 ONTAP tools 之前設定適當的存取控制。



[[overview-of-the-configuration-process]]
== 組態程序總覽

ONTAP tools for VMware vSphere支援建立具有自訂角色的ONTAP使用者。這些定義打包在一個 JSON 檔案中，您可以將其上傳到ONTAP叢集。您可以根據您的環境和安全需求建立使用者並自訂角色。

以下部分從高階層級說明主要的組態步驟。如需更多詳細資訊、請參閱 link:../configure/configure-user-role-and-privileges.html["設定 ONTAP 使用者角色和權限"]。

.1.準備
您必須同時擁有 ONTAP 工具管理員和 ONTAP 叢集的管理認證。

.2.下載 JSON 定義檔案
登入 ONTAP Tools Manager 使用者介面之後，您可以下載包含 RBAC 定義的 JSON 檔案。

.3.建立具有角色的 ONTAP 使用者
登入 System Manager 之後，您可以建立使用者和角色：

. 選擇左側的 * 叢集 * ，然後選擇 * 設定 * 。
. 向下捲動到 *使用者和角色* ，然後選擇 `-->`。
. 在 * 使用者 * 下選取 * 新增 * ，然後選取 * 虛擬化產品 * 。
. 選取本機工作站上的 JSON 檔案並上傳。


.4.設定角色
在定義角色時，您必須做出數項管理決策。如需詳細資訊、請參閱<<使用 System Manager 設定角色>>。



[[configure-the-role-using-system-manager]]
== 使用 System Manager 設定角色

開始使用 System Manager 建立新的使用者和角色，並上傳 JSON 檔案之後，即可根據您的環境和需求自訂角色。



[[core-user-and-role-configuration]]
=== 核心使用者和角色組態

RBAC 定義會封裝為多種產品功能，包括 VSC ， VASA Provider 和 SRA 的組合。您應該選擇需要 RBAC 支援的環境。例如，如果您想要角色支援遠端外掛程式功能，請選取 VSC 。您也需要選擇使用者名稱和相關密碼。



[[privileges]]
=== 權限

根據 ONTAP 儲存設備所需的存取層級，角色權限分為四組。角色所依據的權限包括：

* 探索
+
此角色可讓您新增儲存系統。

* 建立儲存設備
+
此角色可讓您建立儲存設備。它也包含與探索角色相關的所有 Privileges 。

* 修改儲存設備
+
此角色可讓您修改儲存設備。它也包含與探索相關的所有 Privileges ，並建立儲存角色。

* 銷毀儲存設備
+
此角色可讓您銷毀儲存設備。它也包含與探索，建立儲存和修改儲存角色相關的所有 Privileges 。





[[generate-the-user-with-a-role]]
=== 產生具有角色的使用者

選擇好環境的組態選項後，選取 *Add*，ONTAP 即會建立使用者和角色。產生的角色名稱是以下值的串連：

* 在 JSON 檔案中定義的固定首碼值（例如「 OTV_10 」）
* 您選擇的產品功能
* 權限集清單。


.範例
`OTV_10_VSC_Discovery_Create`

新使用者將顯示在 *使用者和角色* 頁面的清單中。請注意，HTTP 和 ONTAPI 兩種使用者登入方式皆受支援。
