---
permalink: automation/create-vvol-workflow.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: 工作流程是完成特定管理工作或目標所需的一或多個步驟順序。 
---
= 建立 VVols 資料存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用新的磁碟區或現有的磁碟區來建立 vVols 資料存放區。您也可以結合現有磁碟區和新磁碟區來建立 vVols 資料存放區。


NOTE: 檢查以確保根集合體未對應至 SVM 。

在建立資料存放區之前產生 JWT Token 、或在 vCenter 上將「最大承載 Token 生命週期」設定為 60 公尺、以增加 SAML Token 到期日。

您需要通過 API 的 x-auth 。您可以從 Swagger 中的驗證新增的 API 產生此 x-auth 。

/virtualization / api/v1/aut/vCenter-login

. 使用新的 Volume 建立 vVols 資料存放區。


使用 ONTAP REST API 取得 Aggregate id 、 storage _id （ SVM uuid ）。
POST /virtualization / api/v1/vCents/cded9ad-6bsd-4c9e-b44G-691250bfe2df/vols/datas存放 區

使用下列 URI 檢查狀態：

+

[listing]
----
`\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
Request Body for NFS 資料存放區

｛
   "name" ： "nfsds1" 、
   " 傳輸協定 " ： "NFS",
   " 平台類型 " ： "aff 、
   "moref" ： "domain-C8" 、
   " 磁碟區 " ： [
      ｛
         "is_existing ：錯、
         "name" ： "vol_nfs_pvt" 、
         "Size_in_MB" ： 2048000 、
         " 空間效率 " ： " 精簡 " 、
         「 Aggregate 」： ｛
            "ID" ： "d7078b3c-3827-4ac9-9273-0a32909455c2"
         } 、
         "QoS" ： ｛
            "min_IOPS " ： 200 、
            " 最大 IOPS " ： 5000
         }
      }
   ] 、
   "storage _backend" ： ｛
      "storage _id" ： "654c67bc-0f75-11e-8a8c-00a09860a3ff"
   }
}

iSCSI 資料存放區的要求本文：
｛
   " 名稱 " ： "iSCSI_CUSTOM_" 、
   " 傳輸協定 " ： "iSCSI" 、
   "platfore_type" ： "e" AFF 、
   "moref" ： "domain-C8" 、
   " 磁碟區 " ： [
       ｛
           "is_existing " ：錯、
           " 名稱 " ： "iSCSI_CUSTOM_" 、
           "Size_in_MB" ： 8034 、
           " 空間效率 " ： " 精簡 " 、
           "Aggregate ： {
               "ID" ： "54fe5dd4-e461-49c8-bb2d-6d62c5d75af2"
           }
       }
   ] 、
   "custom_igroup_name ： "igroup1" 、
   「 storage _backend 」： ｛
                       「 storage _id 」：「 eb9d33ab-1960-11ee-9506-00a0985c6d9b 」 ｝
}
。使用現有磁碟區建立 VVols 資料存放區。

使用 ONTAP REST API 取得 Aggregal_id 和 volume ID 。

 POST /virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores
要求主體

....
 {
"name" : "nfsds2",
"protocol" : "nfs",
"platform_type": "aff",
"moref" : "domain-c8",
"volumes" : [
    {
          "is_existing": true,
          "id": "e632a632-1412-11ee-8a8c-00a09860a3ff"
        }
],
"storage_backend": {
                    "storage_id": "33a8b6b3-10cd-11ee-8a8c-00a09860a3ff"    }
....
}
