---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: 將 vCenter Server 執行個體新增至 VMware vSphere 的 ONTAP 工具，以設定，管理及保護 vCenter Server 環境中的虛擬資料存放區。 
---
= 將 vCenter Server 執行個體新增至ONTAP工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將 vCenter Server 執行個體新增至 VMware vSphere 的 ONTAP 工具，以設定，管理及保護 vCenter Server 環境中的虛擬資料存放區。新增多個 vCenter Server 執行個體時，需要自訂 CA 憑證才能在 ONTAP 工具和每個 vCenter Server 之間進行安全通訊。

.關於這項工作
ONTAP工具與 vCenter Server 集成，可直接從 vSphere 用戶端執行設定、快照和資料保護等儲存任務。

.開始之前
* 請確保 vCenter Server 憑證包含有效的「使用者備用名稱（SAN）」擴展，其中包含 DNS 和 IP 位址項目。例如：
+
[listing]
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
+
如果憑證不包含 SAN 擴充，或者 SAN 擴充不包含正確的 DNS 或 IP 位址值，ONTAP tools 操作可能會因憑證驗證錯誤而失敗。

* vCenter Server 的主網路識別碼（PNID）必須包含在 SAN 詳細資訊中。PNID 和 DNS 名稱應相同，並且可在 DNS 中解析。
* 建議使用完全限定網域名稱（FQDN）部署 vCenter Server，並確保憑證中的 SAN 包含 DNS Name=machine_FQDN，以獲得最佳相容性和支援。
* 如需更多資訊，請參閱 VMware 文件：
+
** https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-authentication/vsphere-security-certificates-authentication/certificate-requirements-for-different-solution-paths-authentication.html["不同解決方案路徑的 vSphere 憑證需求"]
** https://knowledge.broadcom.com/external/article/316601/replace-vcenter-machine-ssl-certificate.html["替換 vCenter Machine SSL 憑證自訂憑證授權單位簽署憑證"]
** https://knowledge.broadcom.com/external/article/406282/error-subject-alternate-name-san-field-d.html["錯誤：主題備用名稱（SAN）欄位不包含 PNID。請提供有效的證書"]




[NOTE]
====
如果 FQDN 不可用，您可以將 PNID 設定為 IP 位址，並將該 IP 位址包含在 SAN 中。但是，VMware 不建議這樣做。

====
.步驟
. 開啟 Web 瀏覽器並前往以下 URL： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 選取 * vCenters * > * Add* 以內建 vCenter Server 執行個體。提供 vCenter IP 位址或主機名稱，使用者名稱，密碼和連接埠詳細資料。
. 在進階選項中，自動取得 vCenter Server 憑證（授權）或手動上傳。
+

NOTE: 您不需要管理員帳戶，即可將 vCenter 執行個體新增至 ONTAP 工具。您可以建立自訂角色，而無需具有有限權限的管理員帳戶。如 link:../concepts/rbac-vcenter-use.html["使用 vCenter Server RBAC 搭配適用於 VMware vSphere 10 的 ONTAP 工具"] 需詳細資訊、請參閱。



將 vCenter Server 執行個體新增至 ONTAP 工具會自動觸發下列動作：

* ONTAP工具將 vCenter 用戶端插件註冊為遠端插件。
* 外掛程式和 API 的自訂 Privileges 會套用至 vCenter Server 執行個體。
* 建立自訂角色以管理使用者。
* 外掛程式會在 vSphere 使用者介面上顯示為捷徑。

