---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: 將 vCenter Server 執行個體新增至 VMware vSphere 的 ONTAP 工具，以設定，管理及保護 vCenter Server 環境中的虛擬資料存放區。 
---
= 將 vCenter Server 執行個體新增至ONTAP工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將 vCenter Server 執行個體新增至 VMware vSphere 的 ONTAP 工具，以設定，管理及保護 vCenter Server 環境中的虛擬資料存放區。新增多個 vCenter Server 執行個體時，需要自訂 CA 憑證才能在 ONTAP 工具和每個 vCenter Server 之間進行安全通訊。

在向 ONTAP 工具管理器註冊 vCenter Server 執行個體時，請確保 vCenter Server 憑證包含有效的主體別名（SAN）擴充功能。SAN 擴充功能必須同時包含 DNS 和 IP 位址項目。例如：

[listing]
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
如果 vCenter Server 憑證不包含 SAN 擴充，或者 SAN 擴充不包含正確的 DNS 或 IP 位址值，ONTAP tools 操作可能會因憑證驗證錯誤而失敗。

.關於這項工作
ONTAP工具與 vCenter Server 集成，可直接從 vSphere 用戶端執行設定、快照和資料保護等儲存任務。

.步驟
. 開啟 Web 瀏覽器並前往以下 URL： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 選取 * vCenters * > * Add* 以內建 vCenter Server 執行個體。提供 vCenter IP 位址或主機名稱，使用者名稱，密碼和連接埠詳細資料。
. 在進階選項中，自動取得 vCenter Server 憑證（授權）或手動上傳。
+

NOTE: 您不需要管理員帳戶，即可將 vCenter 執行個體新增至 ONTAP 工具。您可以建立自訂角色，而無需具有有限權限的管理員帳戶。如 link:../concepts/rbac-vcenter-use.html["使用 vCenter Server RBAC 搭配適用於 VMware vSphere 10 的 ONTAP 工具"] 需詳細資訊、請參閱。



將 vCenter Server 執行個體新增至 ONTAP 工具會自動觸發下列動作：

* ONTAP工具將 vCenter 用戶端插件註冊為遠端插件。
* 外掛程式和 API 的自訂 Privileges 會套用至 vCenter Server 執行個體。
* 建立自訂角色以管理使用者。
* 外掛程式會在 vSphere 使用者介面上顯示為捷徑。

