---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 儲存設備後端是 ESXi 主機用於資料儲存的系統。 
---
= 將儲存後端新增至ONTAP工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用ONTAP tools for VMware vSphere為 ESXi 主機新增和管理儲存後端。您可以部署叢集或 SVM，啟用MetroCluster支持，並驗證憑證以確保安全連線。您可以使用ONTAP工具管理器或 vSphere 用戶端設定儲存後端，監控憑證狀態，並在叢集變更後手動重新發現資源。

若要在本機新增儲存後端，請在ONTAP工具介面中使用叢集或 SVM 憑證。本機儲存後端僅對選定的 vCenter Server 可用。ONTAP工具將 SVM 對應到 vCenter Server 以進行vVols或 VMFS 資料儲存庫管理。對於 VMFS 資料儲存和 SRA 工作流程，您可以使用 SVM 憑證而無需全域映射叢集。

若要新增全域儲存後端，請在ONTAP工具管理器中使用ONTAP叢集憑證。全域儲存後端支援發現工作流程，以識別 vVol 管理所需的叢集資源。在多租用戶環境中，您可以本機新增 SVM 使用者來管理vVols資料儲存。

如果ONTAP中啟用了MetroCluster支持，則將來源叢集和目標叢集都作為本地或全域儲存後端加入。

.開始之前
驗證憑證是否包含有效的主題備用名稱 (SAN) 欄位。  ONTAP系統使用 SAN 欄位來識別叢集和 SVM 管理 LIF。

[role="tabbed-block"]
====
.使用 ONTAP 工具管理器
--

NOTE: 在多租戶設定中，您可以全域新增儲存後端叢集，並在本機新增 SVM 以使用 SVM 使用者認證。

.步驟
. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 從側欄中選擇 * 儲存後端 * 。
. 新增儲存後端，並提供伺服器 IP 位址或 FQDN ，使用者名稱和密碼詳細資料。
+

NOTE: 支援 IPv4 和 IPv6 位址管理階層。

. 自動取得ONTAP叢集證書並授權該證書，或透過瀏覽至其位置手動上傳。
+

NOTE: 如果需要，您可以從維護控制台停用主題備用名稱 (SAN) 驗證。有關說明，請參閱link:../manage/change-valid-flag.html["更改證書驗證標誌"]。

. 如果您新增的儲存後端是MetroCluster配置的一部分， ONTAP工具管理器會顯示一則彈出訊息以新增對等叢集。選擇“*新增*”並提供MetroCluster對等儲存後端的詳細資訊。
+

NOTE: ONTAP系統執行切換和切回後，手動執行ONTAP工具發現。



--
.使用 vSphere 用戶端使用者介面
--

NOTE: vVols資料儲存不支援透過 vSphere Client 使用者介面直接新增 SVM 使用者。

. 登入 vSphere 用戶端。
. 在捷徑頁面中，選取外掛程式區段下方的 * NetApp ONTAP tools* 。
. 從側欄中選擇 * 儲存後端 * 。
. 新增儲存後端，並提供伺服器 IP 位址，使用者名稱，密碼和連接埠詳細資料。
+

NOTE: 您可以使用基於叢集的憑證以及 IPv4 或 IPv6 管理 LIF 新增儲存後端。若要直接新增 SVM 用戶，請提供基於 SVM 的憑證以及 SVM 管理 LIF。如果叢集已加入，則無法再次從該叢集加入 SVM 使用者。

. 自動取得ONTAP叢集證書並授權該證書，或透過瀏覽至其位置手動上傳。
. 如果新增的儲存後端是MetroCluster配置的一部分，ONTAP工具將顯示 *新增MetroCluster對等體* 螢幕。選擇*新增對等*以新增對等儲存後端。
+

NOTE: ONTAP系統執行切換和切回後，手動執行ONTAP工具發現。



.接下來呢？
ONTAP工具更新清單以顯示新的儲存後端。

--
====
ONTAP工具在 *儲存後端* 頁面上列出了新新增的儲存後端。如果憑證在 30 天或更短時間內過期， ONTAP工具會在憑證過期日期列中顯示警告。到期後， ONTAP工具會將儲存後端標記為未知，因為它無法連接到儲存系統。

.相關資訊
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html["將叢集配置為MetroCluster配置"]
