---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: 適用於 VMware vSphere 的 ONTAP 工具會檢查及設定 ESXi 主機多重路徑設定和 HBA 逾時設定、這些設定最適合搭配 NetApp 儲存系統使用。 
---
= 在 ONTAP 工具中設定 ESXi 主機設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置 ESXi 伺服器多路徑和逾時設定有助於維護資料可用性和完整性。如果主路徑不可用，它可以自動故障轉移到備份儲存路徑。



== 設定 ESXi 伺服器多重路徑和逾時設定

VMware vSphere的支援VMware vSphere工具可檢查及設定ESXi主機多重路徑設定、以及最適合搭配NetApp儲存系統使用的HBA逾時設定。ONTAP

.關於這項工作
此過程可能需要一些時間，具體取決於您的設定和系統負載。您可以在「近期任務」面板中查看進度。

.步驟
. 從 VMware vSphere Web 用戶端首頁，選取 * 主機與叢集 * 。
. 在 VMware vSphere Web Client 的捷徑頁面上，選取外掛程式區段下方的 * NetApp ONTAP tools* 。
. 前往 VMware vSphere 外掛程式 ONTAP 工具概觀（儀表板）中的 * ESXi 主機相容性 * 卡。
. 選取 * 套用建議的設定 * 連結。
. 在「套用建議的主機設定」視窗中，選擇要更新以使用NetApp推薦設定的主機，然後選擇「下一步」。
+

NOTE: 您可以展開 ESXi 主機以查看目前的值。

. 在「設定」頁面中、視需要選取建議的值。
. 在摘要窗格中，檢查值並選擇 * 完成 * 。您可以在最近的工作面板中追蹤進度。




== 設定 ESXi 主機值

使用ONTAP tools for VMware vSphere在 ESXi 主機上設定逾時和其他值，以實現最佳效能和故障轉移。它根據NetApp測試設定這些值。

您可以在ESXi主機上設定下列值：



=== HA/CNA 介面卡設定

將下列參數設定為預設值：

* disk.QFullSampleSize.
* disk.QFullThreshold
* Emulex FC HBA逾時
* QLogic FC HBA逾時




=== MPIO 設定

MPIO 設定為NetApp儲存系統選擇最佳路徑。  MPIO 設定選擇最佳路徑並使用它。

對於高效能環境或使用單一 LUN 資料儲存進行測試時，請調整循環 (VMW_PSP_RR) 路徑選擇策略 (PSP) 的負載平衡設定以提高效能。將預設 IOPS 值從 1000 設定為 1。


NOTE: MPIO 設定不適用於 NVMe、NVMe/FC 和 NVMe/TCP 協定。



=== NFS設定

|===


| 參數 | 將此值設為 ... 


| net.TcpipHeapSize. | 32. 


| net.TcpipHeapMax | 1024MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQuesteDepth | 128 或更高版本 


| NFS.HeartbeatMaxFailures | 10 


| NFS.Heartbeat頻率 | 12 


| NFS.Heartbeattimeout | 5 
|===