---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords: create datastore, ONTAP tools NFS VMFS vVols, host cluster datastore provisioning, nconnect datastore settings 
summary: 在主機或主機叢集層級，使用 ONTAP tools 建立 NFS、VMFS 或 vVols 資料存放區。 
---
= 在 ONTAP 工具中建立資料存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您在主機叢集層級建立資料儲存庫時， ONTAP工具會將其掛載到所有目標主機上，並且僅當您擁有所需的權限時才啟用此操作。

*本機資料儲存與 vCenter Server 與 ONTAP 工具管理的資料儲存之間的互通性*

從適用於ONTAP tools for VMware vSphere開始， ONTAP工具為資料儲存區建立巢狀 igroup，其中父 igroup 特定於資料儲存區，子 igroup 對應到主機。您可以從ONTAP系統管理員建立平面 igroup，並使用它們建立 VMFS 資料儲存庫，而無需使用ONTAP工具。參考 https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["管理 SAN 啟動器和 igroup"]了解更多。

在您加入儲存空間並執行資料儲存發現後， ONTAP工具會將 VMFS 資料儲存中的平面 igroup 變更為巢狀 igroup。您不能使用早期的平面 igroup 來建立新的資料儲存。使用ONTAP工具介面或 REST API 來重複使用巢狀 igroup。

[role="tabbed-block"]
====
.建立 VVols 資料存放區
--
從 ONTAP tools for VMware vSphere 10.3 開始，您可以在 ASA r2 系統上建立具有精簡空間效率的 vVols 資料存放區。VASA Provider 在建立 vVol 資料存放區時，會建立一個 Container 和所需的通訊協定端點。VASA Provider 不會為此 Container 指派任何後端 Volume。

.開始之前
* 確保根 Aggregate 未對應至 SVM 。
* 請確定 VASA Provider 已向所選 vCenter 登錄。
* 對於 ASA r2 儲存系統，不需要 SVM 到彙總的對應。


.步驟
. 登入 vSphere Client。
. 右鍵點選主機系統、主機叢集或資料中心，然後選擇 * NetApp ONTAP工具* > * 建立資料儲存*。
. 選擇 vVols 作為 *Datastore type* 。
. 輸入 * 資料存放區名稱 * 和 * 傳輸協定 * 資訊。
+

NOTE: ASA R2 系統支援 VVols 的 iSCSI 和 FC 傳輸協定。

. 選取您要建立資料存放區的儲存 VM 。
. 在*進階選項*下：
+
** 如果選擇*自訂匯出原則*，請先在 vCenter 中對所有物件執行探索程序，然後再繼續。建議不要使用此選項。
** 您可以為 iSCSI 和 FC 傳輸協定選取*自訂啟動器群組*名稱。
+

NOTE: 對於 ASA r2 SVM，不會建立儲存單元（LUN/命名空間），因為資料儲存區只是一個邏輯 Container。



. 在 * 儲存屬性 * 窗格中，您可以建立新的磁碟區或使用現有的磁碟區。不過，您無法合併這兩種類型的磁碟區來建立 VVols 資料存放區。
+
建立新磁碟區時、您可以在資料存放區上啟用 QoS。根據預設、每個 LUN 建立要求都會建立一個磁碟區。對於 ASA r2 儲存系統上的 vVols 資料存放區、請跳過此步驟。

. 在 * 摘要 * 窗格中檢閱您的選擇，然後選取 * 完成 * 。


--
.建立 NFS 資料存放區
--
NFS 資料儲存使用 NFS 協定將 ESXi 主機連接到共享儲存設備。它簡單且靈活，常用於 VMware vSphere 環境中。

.步驟
. 登入 vSphere Client。
. 右鍵點選主機系統、主機叢集或資料中心，然後選擇 * NetApp ONTAP工具* > * 建立資料儲存*。
. 在 * 資料存放區類型 * 欄位中選取 NFS 。
. 在「名稱和協定」窗格中輸入資料儲存名稱、大小和協定資訊。
+
.. 在「進階選項」中選擇「資料儲存叢集」和「Kerberos 驗證」。
+

NOTE: Kerberos 驗證只有在選取 NFS 4.1 傳輸協定時才能使用。

.. 指定資料儲存區的*連線數 (nconnect)*。預設值為 4，可設定範圍為 1 到 8。如果所選值高於目前主機層級的 nconnect 設定，ONTAP tools 將更新主機層級的 nconnect 設定以符合所選值。


. 在「儲存設備」窗格中，選取「平台」和「儲存 VM」。
. 如果在「進階選項」下選擇「自訂匯出原則」，請在 vCenter 中對所有物件執行探索，然後再繼續操作。
+

NOTE: 您不能使用 SVM 的預設或根磁碟區策略建立 NFS 資料儲存庫。

+
** 在「進階選項」中，「非對稱」切換按鈕僅在平台下拉式選單中選擇「效能」或「容量」時才會顯示。但是，「非對稱」選項不適用於 NFS 資料存放區的建立。
** 當您在平台下拉式選單中選擇「任意」選項時，vCenter 中的所有 SVM 均可見。平台設定和非對稱設定不影響可見度。


. 在「儲存屬性」窗格中，選擇用於建立 Volume 的彙總。在「進階選項」中，視需要選擇「空間預留」和「啟用 QoS」。
. 在「摘要」窗格中，審查所選內容，然後選擇「完成」。


ONTAP工具建立 NFS 資料儲存庫並將其掛載到所有主機上。

--
.建立 VMFS 資料存放區
--
VMFS 是一個用於儲存虛擬機器檔案的叢集檔案系統。多個 ESXi 主機可以同時存取相同的 VM 文件，以實現 vMotion 和高可用性功能。

.開始之前
* 為 ONTAP 儲存端的每個傳輸協定啟用服務和生命。
* 對於 ASA r2 儲存系統，不需要 SVM 到彙總的對應。
* 如果您使用的是 NVMe / TCP 傳輸協定，請設定 ESXi 主機：
+
.. 檢閱 https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["VMware相容性指南"]
+

NOTE: VMware vSphere 7.0 U3 及更新版本支援 NVMe / TCP 傳輸協定。不過，建議使用 VMware vSphere 8.0 及更新版本。

.. 檢查網路介面卡 (NIC) 廠商是否支援採用 NVMe/TCP 協定的 ESXi NIC。
.. 根據 NIC 供應商規格為 NVMe/TCP 設定 ESXi NIC。
.. 使用 VMware vSphere 7 版本時、請遵循 VMware 網站上的指示 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["為 NVMe over TCP 介面卡設定 VMkernel Binding"]來設定 NVMe / TCP 連接埠繫結。使用 VMware vSphere 8 版本時、請遵循 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["在 ESXi 上設定 NVMe over TCP"]設定 NVMe / TCP 連接埠繫結。
.. 針對 VMware vSphere 7 版本，請依照第頁的指示 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["啟用透過 RDMA 或 NVMe over TCP 軟體介面卡的 NVMe"]來設定 NVMe / TCP 軟體介面卡。對於 VMware vSphere 8 版本，請遵循 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["透過 RDMA 或 NVMe over TCP 介面卡新增軟體 NVMe"]設定 NVMe / TCP 軟體介面卡。
.. 在 ESXi 主機上執行 link:../configure/discover-storage-systems-and-hosts.html["探索儲存系統與主機"] 行動。如需更多資訊，請參閱 https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["如何使用 vSphere 8.0 Update 1 和 ONTAP 9 。 13.1 設定適用於 VMFS 資料存放區的 NVMe / TCP"]。


* 如果您使用的是 NVMe/FC 通訊協定，請執行下列步驟來設定 ESXi 主機：
+
.. 如果尚未啟用，請在 ESXi 主機上啟用 NVMe over Fabrics (NVMe-oF)。
.. 完成 SCSI 分區。
.. 確保 ESXi 主機和 ONTAP 系統連接在實體層和邏輯層。




要爲 FC 協議配置 ONTAP SVM ，請參閱 https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["設定SVM for FC"]。

如需搭配 VMware vSphere 8.0 使用 NVMe / FC 傳輸協定的詳細資訊 https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["適用於 ESXi 8.x 與 ONTAP 的 NVMe 主機組態"]、請參閱。

有關在 VMware vSphere 7.0 中使用 NVMe/FC 的詳細資訊，請參閱 https://docs.netapp.com/us-en/ontap-sanhost/nvme-esxi-7.html["NVMe / FC主機組態指南ONTAP"]。

.步驟
. 登入 vSphere Client。
. 右鍵點選主機系統、主機叢集或資料中心，然後選擇 * NetApp ONTAP工具* > * 建立資料儲存*。
. 選擇 VMFS 資料存放區類型。
. 在「名稱和協定」窗格中輸入資料存放區名稱、大小和協定資訊。若要將新資料存放區新增至現有 VMFS 叢集，請在「進階選項」中選擇資料存放區叢集。
. 在「儲存設備」窗格中選擇儲存設備 VM。根據需要，在「進階選項」區段中提供「自訂啟動器群組名稱」。您可以為資料儲存區選擇現有的啟動器群組，也可以建立具有自訂名稱的新啟動器群組。
+
選擇 NVMe/FC 或 NVMe/TCP 協定時，系統會建立一個新的命名空間子系統，用於命名空間映射。ONTAP tools 會使用包含資料儲存名稱的自動產生名稱建立命名空間子系統。您可以在 *Storage* 窗格的 *Advanced options* 中的 *custom namespace subsystem name* 欄位中重新命名命名空間子系統。

. 在「儲存屬性」窗格中：
+
.. 從下拉式選項中選取 * Aggregate * 。
+

NOTE: 對於 ASA r2 儲存系統，由於儲存設備是分離的，因此不會顯示*彙總*選項。當您選擇 ASA r2 儲存系統類型 SVM 時、*儲存屬性*頁面會顯示啟用 QoS 的選項。

.. ONTAP工具根據所選協定建立具有精簡空間預留的儲存單元（LUN/命名空間）。
+

NOTE: 從 ONTAP 9.16.1 開始， ASA R2 儲存系統每個叢集最多可支援 12 個節點。

.. 為異質叢集中具有 12 節點 SVM 的 ASA r2 儲存系統選擇 *Performance service level*。如果所選 SVM 是同質叢集或使用 SVM 使用者，則此選項無法使用。
+
「任何」是預設的效能服務層級（ PSL ）值。此設定會使用 ONTAP 平衡放置演算法建立儲存單元。不過，您可以視需要選擇效能或極致選項。

.. 選擇 * 使用現有的 Volume * ， * 視需要啟用 QoS* 選項，並提供詳細資料。
+

NOTE: 在 ASA r2 儲存類型中、磁碟區的建立或選擇不適用於儲存單元建立（LUN/Namespace）。因此、這些選項不會顯示。

+

NOTE: 您不能使用現有磁碟區來建立具有 NVMe/FC 或 NVMe/TCP 協定的 VMFS 資料儲存體。為 VMFS 資料儲存建立新磁碟區。



. 在「*Protection*」視窗中，選擇「*Protect this datastore using SnapMirror replication*」以啟用保護。您可以將資料儲存區新增至現有保護群組或建立新的保護群組。若要建立新的保護群組：
+
.. 請輸入*保護群組名稱*。
.. 設定 SnapMirror 關係。如果選擇自動容錯移轉雙工原則 （AFD），請先設定主機叢集組態設定，然後再繼續。如需詳細資訊，請參閱link:../protect/config-proximity.html["使用 ONTAP tools 設定叢集以保護資料存放區"]。
+

NOTE: 如果所選 Volume 已屬於其他保護設定，則下一個保護頁面將停用，並顯示一則資訊性訊息。如果資料儲存不符合保護資格，則保護選項將停用，並顯示不符合條件的原因。您仍然可以建立未受保護的資料儲存。



. 檢閱 * 摘要 * 窗格中的資料存放區詳細資料，然後選取 * 完成 * 。
+

NOTE: 如果資料存放區受到保護，ONTAP tools 會將其掛載到叢集中的所有主機上。



.結果
ONTAP工具建立 VMFS 資料儲存庫並將其安裝在所有主機上。

--
====