---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用適用於 VMware vSphere 的 ONTAP 工具、安裝適用於 VMware vStorage API for Array Integration （ VAAI\ ）的 NetApp NFS 外掛程式。 
---
= 使用ONTAP工具安裝 NFS VAAI 插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS vStorage API for Array Integration (NFS VAAI) 外掛程式將 VMware vSphere 連接到 NFS 儲存陣列。使用適用ONTAP tools for VMware vSphere安裝 VAAI 外掛程式。這允許 NFS 儲存陣列取代 ESXi 主機處理某些儲存操作。

.開始之前
* 下載 https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["適用於VMware VAAI的NetApp NFS外掛程式"]安裝套件。
* 請確定您擁有 ESXi 主機和 vSphere 7.0U3 最新修補程式或更新版本，以及 ONTAP 9.14.1 或更新版本。
* 掛載 NFS 資料存放區。


.步驟
. 登入 vSphere 用戶端。
. 在外掛程式區段下，選取 * 快速鍵 * > * NetApp ONTAP tools* 。
. 選取 * 設定 * > * NFS VAAI 工具 * 。
. 如果您已經將 VAAI 外掛程式上傳到 vCenter Server，請在 *現有版本* 中選擇 *變更*。如果還沒有，請選擇*上傳*。
. 瀏覽並選取 `.vib`檔案，然後選取 * 上傳 * 將檔案上傳至 ONTAP 工具。
. 選取 * 安裝在 ESXi 主機 * ，選取要安裝 NFS VAAI 外掛程式的 ESXi 主機，然後選取 * 安裝 * 。
+
vSphere Web Client 僅顯示可安裝該插件的 ESXi 主機。您可以在「近期任務」部分監控安裝進度。

. 安裝後手動重新啟動 ESXi 主機。
+
重新啟動 ESXi 主機後，ONTAP tools for VMware vSphere會自動偵測並啟用 NFS VAAI 外掛程式。



.接下來呢？
安裝 NFS VAAI 外掛程式並重新啟動 ESXi 主機後，配置 VAAI 副本卸載的 NFS 匯出策略。確保出口政策規則符合以下要求：

* 相關的ONTAP磁碟區允許 NFSv4 呼叫。
* 根用戶仍為根用戶，且所有連線父磁碟區中都允許使用 NFSv4。
* 在相關的 NFS 伺服器上設定 VAAI 支援選項。


更多信息，請參閱 https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["為 VAAI 複本卸載設定正確的 NFS 匯出原則"]知識庫文章。

.相關資訊
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["支援VMware vStorage over NFS"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["啟用或停用 NFSv4.0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["ONTAP 支援 NFSv4.2"]
