---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 適用於 VMware vSphere 的 ONTAP 工具可管理主機叢集的保護。 
---
= 在 ONTAP 工具中保護主機叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於 VMware vSphere 的 ONTAP 工具可管理主機叢集的保護。屬於所選 SVM 並掛載於叢集一或多個主機上的所有資料存放區、都會受到主機叢集的保護。

.開始之前
在保護主機群集之前，請確保滿足以下要求：

* 主機叢集僅包含來自單一 SVM 的資料儲存庫。
* 主機群集上的資料儲存體未安裝在群集外的主機上。
* 主機叢集上掛載的資料儲存是採用iSCSI或FC協定的VMFS資料儲存。您不能將vVols、NFS 或 VMFS 資料儲存與 NVMe/FC 和 NVMe/TCP 協定一起使用。
* 基於主機上掛載的FlexVol/LUN 磁碟區的資料儲存不屬於任何一致性群組。
* 基於主機上掛載的FlexVol/LUN 磁碟區的資料儲存庫不屬於任何SnapMirror關係。
* 主機群集至少包含一個資料儲存區。


.步驟
. 登入 vSphere 用戶端。
. 右鍵點選主機叢集並選擇 * NetApp ONTAP工具* > *保護叢集*。
. 在保護叢集視窗中，系統會自動填入資料儲存類型和來源儲存虛擬機器（VM）的詳細資料。選擇資料儲存連結以查看受保護的資料儲存。
. 選取 * 新增關係 * 。
. 在 * 新增 SnapMirror 關係 * 視窗中、選取 * 目標儲存虛擬機器 * 和 * 原則 * 類型。
+
原則類型可以是「非同步」或「自動化的 FailOverDuplex 」。

+
當您將 SnapMirror 關係新增為 AutomatedFailOverDuplex 類型原則時，您必須將目標儲存 VM 新增為儲存後端，以部署適用於 VMware vSphere 的 ONTAP 工具。

+
在 AutomatedFailOverDuplex 策略類型中，有統一和非統一主機配置。當您選擇*統一主機配置*切換按鈕時，主機啟動器群組配置將會隱式複製到目標網站上。有關詳細信息，請參閱link:../concepts/ontap-tools-concepts-terms.html["關鍵概念與詞彙"] 。

. 如果您選擇使用非一致的主機組態、請為該叢集內的每個主機選取主機存取（來源 / 目標）。
. 選取*「Add*」。
. 您可以使用*修改主機叢集保護*操作來編輯主機叢集保護。您可以使用省略號選單選項來編輯或刪除關係。
. 選擇 * 保護 * 按鈕。
+
系統會建立一個帶有作業 ID 詳細資訊的 vCenter 任務，並在最近任務面板中顯示其進度。這是一個非同步任務；使用者介面僅顯示請求提交狀態，並不等待任務完成。

. 若要查看受保護的主機集群，請前往 * NetApp ONTAP工具* > *保護* > *主機集群關係*。選擇一致性群組以查看其容量、關聯資料儲存和子一致性群組。


[NOTE]
====
如果需要在建立後一小時內刪除保護，請先執行儲存發現。

====
.相關資訊
https://www.vmware.com/docs/vmware-vsphere-metro-storage-cluster-vmsc["VMware vSphere Metro 儲存叢集 (vMSC)"^]
