---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.5, ONTAP tools for VMware vSphere' 
summary: 了解適用於ONTAP tools for VMware vSphere中提供的新功能。 
---
= 適用於ONTAP tools for VMware vSphere的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解適用於ONTAP tools for VMware vSphere中提供的新功能。

* *平台資質*


ONTAP tools for VMware vSphere增加了對ASA r2 系統的支持，從而提供了與最新硬體和軟體配置的兼容性。此版本還包括與ONTAP 9.16.1 和 9.17.1 的集成，擴展了支援的環境。

* *VMware 資格和認證*


ONTAP tools for VMware vSphere符合目前的 VMware 互通性認證標準，支援 ESXi 主機和 vCenter Server。

* * MetroCluster支援*


此版本引入了對MetroCluster配置的支持，增強了高可用性和災難復原功能。

* *安全性和憑證管理*


此版本引入了自簽名憑證的簡化管理，增強了使用者體驗並提高了對安全標準的遵守。它提供了改進的憑證驗證工作流程，以保護ONTAP tools for VMware vSphere通訊的ONTAP和 ONTAP 工具。

* *複製增強*


此版本支援具有分層一致性組的 VMFS 複製，包括ASA r2 系統中的 SRA 和SnapMirror活動同步。它支援零 RPO 備份，以提高資料保護和復原。

* *升級和遷移*


從先前版本的ONTAP tools for VMware vSphere到ONTAP tools for VMware vSphere的升級和遷移過程旨在無縫且高效，從而最大限度地減少停機時間並確保平穩過渡。



== 支援的ONTAP平台和 vCenter Server 版本

有關版本相容性的最新詳細信息，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["NetApp 互通性對照表工具"^]。
