---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords: ONTAP tools certificates, VASA provider certificate, vCenter certificate trust, manage appliance certificates 
summary: 管理 ONTAP tools 和 VASA Provider 憑證、續訂預設憑證，或替換為自訂 CA 憑證。 
---
= 管理 ONTAP tools 憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在部署過程中，預設會為ONTAP工具和 VASA 提供者產生自簽章憑證。您可以使用ONTAP工具管理器介面來續訂此憑證或將其替換為自訂 CA 憑證。在多重 vCenter 部署中，必須使用自訂 CA 憑證。


WARNING: 如果憑證過期且未及時續期，ONTAP tools 將停止運作。請在憑證過期前續期，以確保持續運作並防止服務中斷。

.開始之前
在開始之前，您應該準備好以下物品：

* 網域名稱對應至 ONTAP tools 的 IP 位址。
* 成功執行網域名稱 nslookup 查詢，確認其解析到正確的 IP 位址。
* 使用網域名稱和ONTAP工具 IP 位址建立的憑證。



NOTE: ONTAP tools 的 IP 位址應對應到完整網域名稱 （FQDN）。憑證的主旨或主旨備用名稱中應包含與 ONTAP tools IP 位址對應的 FQDN。


NOTE: 您無法從 CA 簽署的憑證切換至自我簽署的憑證。

[role="tabbed-block"]
====
.升級 ONTAP 工具憑證
--
ONTAP 工具索引標籤會顯示憑證類型（自我簽署 /CA 簽署）和網域名稱等詳細資料。在部署期間，預設會產生自我簽署的憑證。您可以續約憑證或將憑證升級至 CA 。

.步驟
. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 選取 * 憑證 * > * ONTAP 工具 * > * 更新 * 以更新憑證。
+
如果憑證已過期或即將過期，您可以進行續約。續訂選項適用於自簽名憑證或 CA 簽章憑證。在彈出的視窗中，請提供伺服器憑證、私鑰、根 CA 和中間憑證的詳細資訊。

+

NOTE: 系統將會離線，直到憑證續約為止，您將登出 ONTAP 工具管理員介面。

. 若要將自我簽署的憑證升級為自訂 CA 憑證，請選取 * 憑證 * > * ONTAP 工具 * > * 升級至 CA* 選項。
+
.. 在快顯視窗中，上傳伺服器憑證，伺服器憑證私密金鑰，根 CA 憑證和中繼憑證檔案。
.. 輸入對應到 ONTAP tools IP 位址（以前稱為負載平衡器 IP）的 FQDN（您為此 IP 位址產生了此憑證），並升級憑證。
+

NOTE: 系統將會離線，直到升級完成為止，您將會登出 ONTAP 工具管理員介面。





--
.升級 VASA Provider 憑證
--
VMware vSphere 的 ONTAP 工具是以 VASA Provider 的自我簽署憑證來部署。有了這項功能、 VVols 資料存放區只能管理一個 vCenter Server 執行個體。當您管理多個 vCenter Server 執行個體並想要在其中啟用 vVols 功能時，您需要將自我簽署的憑證變更為自訂 CA 憑證。

.步驟
. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 選取 * 憑證 * > * VASA Provider* 或 * ONTAP 工具 * > * 更新 * 以更新憑證。
. 選取 * 憑證 * > * VASA Provider* 或 * ONTAP 工具 * > * 升級至 CA* ，將自我簽署的憑證升級為自訂 CA 憑證。
+
.. 在快顯視窗中，上傳伺服器憑證，伺服器憑證私密金鑰，根 CA 憑證和中繼憑證檔案。
.. 輸入對應到 ONTAP tools IP 位址（以前稱為負載平衡器 IP）的 FQDN（您為此 IP 位址產生了此憑證），並升級憑證。
+

NOTE: 系統將會離線，直到升級完成為止，您將會登出 ONTAP 工具管理員介面。





--
.重新整理 ONTAP tools 服務憑證
--
從 ONTAP tools 10.5 開始，憑證有效期限從 10 年縮短至 1 年。從 ONTAP tools 10.5P2 開始，在 ONTAP tools 升級期間，內部服務通訊憑證會自動續期，閘道自我簽署憑證也會重新整理。

當您收到內部憑證即將過期的警報，或 ONTAP tools 一年內未升級時，可以使用此維護控制台選項手動重新整理內部服務通訊憑證。從 ONTAP tools 10.5P2 開始，升級會自動續訂這些憑證。重新整理後的憑證繼續使用一年有效期（365 天），有助於符合稽核要求。

.步驟
. 登入 vCenter 伺服器。
. 找到 ONTAP tools 虛擬機器並開啟 Web 主控台。
. 請使用 `maint`憑證登入。
. 進入 `2`選擇“系統配置”。
. 輸入 `9`以選擇 *Refresh ONTAP tools services certificates*。



WARNING: 此行動將重新啟動所有服務，可能會導致停機或中斷。若要繼續，請鍵入以確認警告 `y`，然後重新整理程序即會開始。

--
====