---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: delete datastore, ONTAP tools datastore removal, delete NFS VMFS vVol datastore, VMware datastore cleanup 
summary: 刪除 NFS、VMFS 或 vVols 資料存放區，並在移除前審查使用它的虛擬機器。 
---
= 在 ONTAP 工具中刪除資料存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用此工作，透過 vCenter Server 中的 ONTAP tools 來刪除 NFS、VMFS 或 vVols 資料儲存庫。刪除行為和清理選項因資料儲存庫類型而異。

.NFS 和 VMFS 資料存放區的刪除行為
* 您無法刪除虛擬機器使用的資料儲存。
* 對於受保護的主機叢集，適用額外的保護限制。


.vVols 資料存放區的刪除行為
對於 vVols 資料存放區，將執行以下動作：

* vVol 容器已卸載。
* 如果 igroup 未使用，則會從 igroup 中移除其啟動器。
* vVol 容器已被刪除。
* 彈性卷留在儲存陣列上。


對於 vVols 資料存放區，只有當所選資料存放區上不存在任何 vVols 時，才能刪除該資料存放區。

.開始之前
* 請確認資料儲存未被虛擬機器使用。
* 檢查資料儲存是否屬於受保護的主機叢集。
* 決定在刪除資料存放區期間是否刪除 ONTAP 叢集上的備份 Volume。


[cols="1,1,2,2"]
|===
| 資料儲存類型 | 您能將其刪除嗎？ | 主要阻塞條件 | ONTAP 清理選項 


| NFS | 是的 | 資料儲存區正被虛擬機器使用。 | 您可以在適用情況下選擇「刪除 ONTAP 叢集上的 Volume」。 


| VMFS | 是的 | 資料儲存正被虛擬機器使用，或存在主機叢集保護限制。 | 您可以選擇 *Delete volumes on ONTAP cluster*。對於 ONTAP 儲存設備上的受保護主機叢集，不支援從 ONTAP 刪除 Volume。 


| vVols | 是的，有條件地 | 資料存放區上存在一個或多個 vVols。 | 您可以選擇從 ONTAP 移除 Volume，但 ASA r2 除外，因為此工作流程不支援從 ONTAP 刪除後端 Volume。 
|===
.步驟
. 登入 vSphere Client。
. 右鍵點選主機系統、主機叢集或資料中心，然後選擇 * NetApp ONTAP工具* > * 刪除資料儲存*。
+

NOTE: 您無法刪除虛擬機器使用的資料存放區。請先將虛擬機器移至另一個資料存放區，再進行刪除。

+

NOTE: 如果資料儲存是受保護主機叢集的一部分，請在刪除之前審查保護限制。

+
.. 對於 NFS 或 VMFS 資料存放區，畫面會顯示一個對話框，其中列出使用該資料存放區的虛擬機器。
.. 如果沒有虛擬機器與 VMFS 資料儲存關聯，則會顯示確認對話方塊。如果啟用了主機叢集保護並且存在 Automated Failover Duplex (AFD) 關係，則可以清理次要儲存設備元素。
.. 對於 ASA r2 儲存設備系統上的受保護 VMFS 資料存放區，請先移除保護再刪除。從 ONTAP 9.17.1 和 ONTAP tools for VMware vSphere 10.5 開始，您可以刪除受保護的資料存放區。
+
對於使用 Automated Failover Duplex （AFD） 的最後一個資料存放區刪除作業，ONTAP tools 會顯示此訊息：*資料存放區受到保護。刪除前將移除保護。*

+
如果刪除保護群組中最後一個受保護的資料存放區，ONTAP tools 會顯示一則訊息，指出刪除最後一個資料存放區會導致資料存放區不受保護。

.. 對於vVols資料存儲，僅當不存在vVols時才可以刪除資料儲存。  *刪除資料儲存*對話方塊包含從ONTAP叢集中刪除磁碟區的選項。
.. 對於 ASA r2 儲存設備系統上的 vVols 資料存放區，您無法使用 *刪除資料存放區* 選項從 ONTAP 刪除備份 Volume。


. 若要刪除 ONTAP 儲存設備上的備份磁碟區、請選取 * 刪除 ONTAP 叢集上的磁碟區 * 。
+

NOTE: 對於屬於受保護主機叢集的 ONTAP 儲存設備上的 VMFS 資料存放區，您無法從 ONTAP 叢集中刪除該 Volume。



刪除 NFS、VMFS 或 vVols 資料儲存區時，父 igroup 仍保留在 ONTAP 系統中。未對應到任何 LUN 的子 igroup 將會自動刪除。ONTAP tools 每天都會執行清理作業，移除未對應的預設父 igroup。請在 ONTAP 中手動刪除自訂父 igroup。ONTAP tools 無法重複使用已失效的父 igroup。
