---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords: scale ONTAP tools appliance, enable high availability, ONTAP tools HA configuration, appliance scaling settings 
summary: 使用 ONTAP tools Manager 垂直擴充 ONTAP tools 應用裝置並設定高可用性 （HA）。 
---
= 垂直擴充 ONTAP tools 並啟用高可用性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 ONTAP tools Manager 垂直擴充您的應用裝置並設定高可用性 （HA）。預設情況下，ONTAP tools for VMware vSphere 部署為單一節點、非 HA 組態。

.開始之前
* 確保您的 OVA 模板與 Node 1 （初始部署節點）的版本相符。
* 在 Hypervisor 上啟用 CPU 熱新增和記憶體容量熱插拔。這些功能是垂直擴充應用裝置和啟用 HA 所必需的。對於 ONTAP tools 10.6 及更新版本，這些功能預設為啟用。對於早期版本，請在垂直擴充或啟用 HA 之前啟用這些功能。
* 在 vCenter Server 中，將災難恢復服務 (DRS) 自動化層級設定為部分自動化。HA 部署完成後，回復為完全自動化。
+

NOTE: 您只能增加節點規模，不能減少。超小型 （XS） 部署會限制某些服務。



.步驟
. 啟動 ONTAP tools Manager： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您的 ONTAP tools 系統管理員憑證登入。
. 從總覽部分選擇 *Edit Appliance Settings*。
. 在「組態」部分，選擇新的節點大小，然後切換 HA 交換器以啟用高可用性。
. 在「HA 設定」頁面上，驗證以下內容：
+
** 內容庫與 ONTAP tools 虛擬機器所在的 vCenter Server 位於同一伺服器上。
** ONTAP tools 虛擬機器部署在叢集或資源池，而不是直接部署在 ESXi 主機上。
+

IMPORTANT: 啟用 HA 後，無法回復到非 HA 單節點組態。



. 在 *HA 設定* 部分，輸入節點 2 和 3 的網路詳細資料。ONTAP tools 支援 HA 模式下的三個節點。
+
ONTAP tools 會預先填入大多數欄位，其中包含節點 1 的網路設定。您可以在完成精靈之前編輯這些值。只有當管理節點上啟用了 IPv6 時，IPv6 位址條目才可用。請確保每個 ESXi 主機僅託管一個 ONTAP tools VM。

. 審查摘要並按一下「儲存」。


.結果
應用裝置開始擴充並啟用 HA。您可以在*總覽*頁面監控進度，或使用工作 ID 從*工作*檢視追蹤工作。

如果 HA 部署失敗且狀態為「New」，請刪除 vCenter 中失敗的虛擬機器並重試。

在此過程中，請審查 *Alerts* 索引標籤，以了解任何警告或問題。
