---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 ONTAP 工具管理員變更管理員密碼。 
---
= 編輯應用裝置設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 ONTAP 工具管理程式來擴充節點大小，管理服務，並將適用於 VMware vSphere 的 ONTAP 工具升級為高可用度（ HA ）設定。

ONTAP 工具應用裝置最初部署在單一節點非 HA 組態中。您可以在 * 編輯應用裝置設定 * 視窗中編輯組態。

*開始之前*

確保您提供的 OVA 範本與第一個節點具有相同的 OVA 版本。

.步驟
. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://loadBalancerIP:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 在概述區段中選取 * 編輯應用裝置設定 * 。
. 在 * 服務 * 區段中，您可以根據需求啟用選用服務，例如 VASA Provider ， VVols 組態匯入及災難恢復（ SRA ）。
+
首次啟用服務時，您需要建立 VASA Provider/SRA 認證。這是用來在 vCenter Server 上登錄或啟用 VASA Provider/SRA 服務。

+

NOTE: 若要停用任何選用服務，請確定沒有由 ONTAP 工具管理的 vCenter Server 正在使用這些服務。

+
* 只有在啟用 VASA Provider 服務時，才會顯示允許匯入 vVols 組態 * 選項。此選項可讓 vVols 資料從 ONTAP tools 9.x 移轉至 ONTAP tools 10.3 。

. 在 * 組態 * 區段中，您可以根據需求來擴充每個 ONTAP 工具節點大小，並啟用 HA 組態。您需要 vCenter Server 認證才能進行任何變更。
+
當 ONTAP 工具處於 HA 組態時，您可以變更內容庫詳細資料。您應該再次提供新編輯提交的密碼。

+

NOTE: 您只能增加 ONTAP 工具節點大小。您無法將節點從目前的大小向下擴充至較小的大小。非 HA 支援的組態上限為中。對於 HA ，支援中大型組態。

. 使用 HA 切換按鈕來啟用 HA 組態。當您選擇 HA 組態時， HA 相關輸入會出現一個額外的 * HA 設定 * 頁面。
+
** 內容庫應屬於執行 ONTAP 工具節點 VM 的同一個 vCenter Server 。 vCenter Server 認證可用於驗證及下載應用裝置變更的 OVA 範本。
** 若要啟用 HA 部署，不應將裝載 ONTAP 工具的虛擬機器直接部署在 ESXi 主機上。而是應該部署在叢集或資源集區上。
** 啟用後，您就無法從 HA 組態還原為非 HA 單一節點組態。


. 在 * 編輯設備設定 * 視窗的 * HA 設定 * 區段中，您可以輸入節點 2 和節點 3 的詳細資料。節點 1 是部署為 OVA 一部分的 ONTAP 工具預設節點。適用於 VMware vSphere 的 ONTAP 工具可在 HA 設定中支援三個節點。
+

NOTE: 大部分的輸入選項都預先填入節點 1 網路詳細資料，以方便工作流程。不過，您可以先編輯輸入資料，再瀏覽精靈的最後一頁。只有在第一個節點上啟用 IPv6 位址時，才能輸入其他兩個節點的 IPv6 詳細資料。

+
確保 ESXi 主機只包含一個 ONTAP 工具 VM 。每次移至下一個視窗時，都會驗證輸入。

. 在 * 摘要 * 區段中，檢閱詳細資料，然後選取 * 儲存 * 以套用變更。


「 * 總覽 * 」頁面會顯示部署的狀態。您也可以使用工作 ID ，從工作檢視中追蹤編輯設備設定工作狀態。

如果 HA 部署失敗，且新節點的狀態顯示為「 New 」（新增），則在重新嘗試啟用 HA 作業之前，請先刪除 vCenter 中的新 VM 。

左側面板上的 * 警示 * 索引標籤列出適用於 VMware vSphere 的 ONTAP 工具警示。
