---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 您可以編輯受保護主機叢集的 SnapMirror 關係。您可以新增、修改及刪除關聯。不過、您無法編輯一致性群組名稱。 
---
= 在 ONTAP 工具中修改受保護的主機叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在單一工作流程中變更主機叢集的保護設定。支援以下更改：

* 將新的資料存放區或主機新增至受保護的叢集。
* 將新的 SnapMirror 關聯新增至保護設定。
* 從保護設定中刪除現有的 SnapMirror 關聯。
* 修改現有的 SnapMirror 關係。



NOTE: 在建立、編輯或刪除主機群集的保護後，您需要執行儲存發現以反映變更。如果您不執行儲存發現，則變更將在觸發定期儲存發現後反映出來。



== 監控主機叢集保護

監控每個受保護主機叢集的保護狀態、 SnapMirror關係、資料儲存庫和SnapMirror狀態。

.步驟
. 登入 vSphere 用戶端。
. 前往 * NetApp ONTAP工具* > *保護* > *主機叢集關係*。
+
保護列顯示一個圖標，表示保護狀態。

. 將游標移至圖示上方、即可查看更多詳細資料。




== 新增資料存放區或主機

使用 vCenter 使用者介面在受保護的叢集上新增主機或建立資料儲存區。

.步驟
. 登入 vSphere 用戶端。
. 若要編輯受保護叢集的內容、您也可以
+
.. 前往 * NetApp ONTAP工具 * > * 保護 * > * 主機叢集關係 *，選擇叢集旁的省略號選單，然後選擇 * 編輯 * 或
.. 右鍵點選主機叢集並選擇 * NetApp ONTAP工具* > *保護叢集*。


. 如果您在 vCenter 使用者介面中建立資料儲存區，它將顯示為不受保護。您可以在對話方塊中查看叢集中的所有資料儲存及其保護狀態。選擇“*保護*”按鈕以啟用保護。
+

NOTE: 在 vCenter Server 使用者介面中建立資料儲存後，在概覽頁面上選擇「發現」以將該資料儲存顯示為主機群集中需要保護的候選對象。下一次定期保護發現後，保護狀態將更新為受保護。

. 如果新增的 ESXi 主機，保護狀態將顯示為部分受保護。選擇SnapMirror設定下的省略號選單，然後選擇 *編輯* 設定新新增的 ESXi 主機的接近度。
+

NOTE: 對於非同步關係， ONTAP工具不支援編輯，因為無法將第三站點的目標 SVM 新增至相同執行個體。若要修改關係配置，請使用 System Manager 或目標 SVM 上的 CLI。

. 進行更改後，選擇*儲存*。
. 您可以在 * 保護叢集 * 視窗中看到變更。


ONTAP工具會建立一個 vCenter 任務，您可以在 *最近任務* 面板中追蹤其進度。



== 新增 SnapMirror 關係

.步驟
. 登入 vSphere 用戶端。
. 若要編輯受保護叢集的內容、您也可以
+
.. 前往 * NetApp ONTAP工具 * > * 保護 * > * 主機叢集關係 *，選擇叢集對應的省略號選單，然後選擇 * 編輯 * 或
.. 右鍵點選主機叢集並選擇 * NetApp ONTAP工具* > *保護叢集*。


. 選取 * 新增關係 * 。
. 將新關係新增為 * 非同步 * 或 * 自動化的 FailOverDuplex* 原則類型。
. 選取 * 保護 * 。
+
您可以在 * 保護叢集 * 視窗中看到變更。



ONTAP工具會建立一個 vCenter 任務，您可以在 *最近任務* 面板中追蹤其進度。



== 刪除現有的 SnapMirror 關係

若要刪除SnapMirror非同步關係，請確保將輔助站點 SVM 或叢集新增為適用ONTAP tools for VMware vSphere中的儲存後端。您不能一次刪除所有SnapMirror關係。刪除關係也會從ONTAP叢集中刪除對應的關係。當您刪除自動故障轉移雙工SnapMirror關係時​​，系統將取消目標資料儲存的對應並從目標ONTAP叢集中刪除一致性群組、LUN、磁碟區和 igroup。

當您刪除關係時，系統會重新掃描輔助網站以從主機中刪除未對應的 LUN 作為活動路徑。

.步驟
. 登入 vSphere 用戶端。
. 若要編輯受保護叢集的內容、您也可以
+
.. 前往 * NetApp ONTAP工具 * > * 保護 * > * 主機叢集關係 *，選擇叢集對應的省略號選單，然後選擇 * 編輯 * 或
.. 右鍵點選主機叢集並選擇 * NetApp ONTAP工具* > *保護叢集*。


. 選取 SnapMirror 設定下的省略符號功能表，然後選取 * 刪除 * 。
+
** 如果刪除受保護主機叢集的基於非同步策略類型的關係，則必須手動從第三儲存叢集中刪除儲存元素。儲存元素包括一致性群組、磁碟區（用於ONTAP系統）、儲存單元（LUN/命名空間）和快照。
** 如果刪除受保護主機叢集的基於自動故障轉移雙工 (AFD) 策略的關係，則可以選擇直接從介面刪除輔助儲存上的相關儲存元素。
** 如果您刪除基於自動故障轉移雙工 (AFD) 政策的關係，且一致性群組現在是針對應用程式層級備份的分層結構，則會出現有關備份影響的警告。確認繼續。確認後，刪除輔助儲存上關聯的儲存元素。如果您不刪除它們，它們將保留在輔助網站上。




ONTAP工具會建立一個 vCenter 任務，您可以在 *最近任務* 面板中追蹤其進度。



== 修改現有的 SnapMirror 關係

若要修改SnapMirror非同步關係，請確保將輔助站點 SVM 或叢集新增為適用ONTAP tools for VMware vSphere中的儲存後端。對於自動故障轉移雙工SnapMirror關係，您可以更新主機鄰近度以實現統一配置，或更新主機存取以實現非統一配置。不支援在非同步和自動故障轉移雙工策略類型之間進行變更。您可以為叢集中新發現的主機配置鄰近度或存取設定。


NOTE: 您無法編輯現有的SnapMirror非同步關係。

.步驟
. 登入 vSphere 用戶端。
. 若要編輯受保護叢集的內容、您也可以
+
.. 前往 * NetApp ONTAP工具 * > * 保護 * > * 主機叢集關係 *，選擇叢集對應的省略號選單，然後選擇 * 編輯 * 或
.. 右鍵點選主機叢集並選擇 * NetApp ONTAP工具* > *保護叢集*。


. 如果選擇了 AutomatedFailOverDuplex 策略類型，請新增主機鄰近度或主機存取詳細資訊。
. 選擇 * 保護 * 按鈕。


ONTAP工具建立 vCenter 任務。在*最近任務*面板中追蹤其進度。
