---
permalink: manage/manage-vcenter.html 
sidebar: sidebar 
keywords: manage vCenter instances, add remove vCenter, ONTAP tools vCenter credentials, vCenter certificate management 
summary: 使用 ONTAP tools 管理 vCenter 執行個體，以控制主機、虛擬機器和儲存設備後端。 
---
= 在ONTAP工具中管理 vCenter Server 實例
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter 伺服器執行個體是集中管理平台，可用於控制主機、虛擬機器和儲存設備後端。在 ONTAP tools 中，您可以解除儲存設備後端關聯、修改執行個體詳細資料、移除執行個體以及續約 vCenter 伺服器憑證。



[[dissociate-storage-backends-from-a-vcenter-server-instance]]
== 將儲存設備後端與 vCenter Server 執行個體分離

vCenter Server 清單頁面會顯示相關的儲存後端數量。每個 vCenter Server 執行個體都可以選擇與儲存後端建立關聯或取消關聯。

.步驟
. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 從側邊欄選取 *vCenters*。
. 選取您要與儲存設備後端關聯或取消關聯的 vCenter Server 的垂直省略號。
. 選擇 * 取消關聯儲存後端 * 。




[[modify-a-vcenter-server-instance]]
== 修改 vCenter Server 執行個體

請完成下列步驟以修改 vCenter Server 執行個體。

. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 從側邊欄選取 *vCenters*。
. 選取您要修改的 vCenter Server 的垂直省略符號，然後選取 * 修改 *。
. 在「修改 vCenter」視窗中，輸入使用者名稱、密碼和連接埠詳細資料。
. 上傳憑證並選取 *Modify*。




[[remove-a-vcenter-server-instance]]
== 移除 vCenter Server 執行個體

即使資料儲存和儲存後端仍然關聯，您也可以移除 vCenter Server 執行個體。「移除 vCenter」對話方塊會根據 vCenter Server 的目前狀態引導您完成所需的任何操作。


NOTE: 強制刪除只會移除 ONTAP tools 中繼資料。它不會移除 ONTAP 儲存設備物件（Volume 或 LUN）、vSphere 資料存放區或虛擬機器。

.開始之前
如果 vCenter 伺服器包含 vVols 資料存放區或受保護的資料存放區，則強制刪除將被封鎖。繼續之前：

* 移除或移轉所有 vVols 資料存放區。
* 取消所有受保護資料儲存的保護。
* 請確保沒有正在執行的探索工作。如果探索工作正在進行中，強制刪除作業將無法執行。



NOTE: 與其他 vCenter Server 執行個體共享的全域儲存設備後端將予以保留。僅移除與已刪除的 vCenter Server 的關聯。

.步驟
. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 從側邊欄選取 *vCenters*。
. 選擇所需 vCenter Server 的垂直省略號，然後選擇 *移除*。
. 在「移除 vCenter」對話方塊中，審查 vCenter Server 的狀態並完成任何必要的動作。
+
對話行為取決於 vCenter 伺服器的狀態：

+
[cols="2,2,3"]
|===
| 狀態 | 對話行為 | 所需行動 


| 沒有 vVols 或受保護的資料存放區，但儲存設備後端已關聯。 | 對話方塊顯示關聯的儲存設備後端和資料儲存的數量。 | 選擇 *從此 vCenter Server 移除所有儲存設備成品* 和 *我瞭解相關的資料存放區將不再由 ONTAP tools 管理*。 


| 沒有 vVols 資料儲存、受保護的資料儲存或儲存設備後端 | 對話框確認移除。 | 無需採取其他行動。 
|===
. 選擇 *Force delete*。
. 確認行動。


.結果
ONTAP tools 會自動執行下列動作：

* 外掛程式已取消註冊。
* 移除外掛程式權限和外掛程式角色。


vCenter 伺服器執行個體不再由 ONTAP tools 管理。

如果 vCenter Server 在刪除過程中無法存取：

* ONTAP tools 會移除 vCenter Server 記錄。
* 外掛程式未取消登錄。
* 螢幕上會顯示警告訊息。
* 您必須手動從 VMware vCenter Server 中取消註冊該外掛程式。




[[renew-vcenter-server-certificate]]
== 更新 vCenter Server 憑證

ONTAP工具會在 vCenter 憑證即將到期或已過期時通知您。更新 vCenter 憑證後，請依照下列步驟將新憑證上傳至ONTAP工具：

. 登入ONTAP工具遠端診斷 shell。
. 從診斷 shell 取得更新後的 vCenter 憑證：
+
[listing]
----
echo | openssl s_client connect <vcenter>:443 2>&1 | sed -n '/-BEGIN CERTIFICATE/,/END CERTIFICATE/p'
----
. 確認憑證為 Base 64 ASCII 格式，並包含起始行和結束行，例如：
+
[listing]
----
---{}BEGIN CERTIFICATE{}---
MIIFUzCCA7ugAwIBAgIJANOgLapcl5oSMA0GCSqGSIb3DQEBCwUAMIGJMQwwCgYD
VQQDDAN2YzExFDASBgoJkiaJk/IsZAEZFgRkZW1vMRUwEwYKCZImiZPyLGQBGRYF
bG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRwwGgYDVQQK
DBN2YzEuZGVtby5uZXRhcHAuY29tMQwwCgYDVQQLDANMT0QwHhcNMjQwNDA1MTgw
NTE4WhcNMjYwNDA1MTgwNTE4WjBzMRwwGgYDVQQDDBN2YzEuZGVtby5uZXRhcHAu
Y29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJ
UGFsbyBBbHRvMQ8wDQYDVQQKDAZOZXRBcHAxDDAKBgNVBAsMA0xPRDCCAaIwDQYJ
KoZIhvcNAQEBBQADggGPADCCAYoCggGBALU8OCWMtA2gvIC/OTw/7xucvPVuM+b8
DhzvNpQ2phjfr6ctEhbntPpqPdu+t2CKK7l0mzg3D9cJ/rvMvdDDXr0tgaD1oi2u
ZDW0CaF0QhLOpNfRXMoogBZ66csEhViAy3CHTcOse770mA/PyoHgrCPZngVlZIiQ
TIWpdQMbEEzFIkrLfC70UW2MzfublrsH7Dn/kOu/iCSlVJWixKf7SmZtVQ5ZxBTD
UlJSiqoX1eRXGyunArEvrIpOY9kkKXUElm3hGnk/ZmiuBJ+HqUYqYW+H+7vE3lKa
6NEqDX+tZotxTx2bXMjeiIWU30ZbshgeXlIG9qc49clBoC9iGjavhctOcaXg/W3h
dLKK5ds3rpRERgMg6VMkrfiqAJuiq+b3sTvXMAul/3hL7hz5QABAE/hP4ZvIHV02
WWDQRLiuVFAcDAyvCrO9Irx0Gk1RyRShKYakdWxZ3hhMdLuGq0yvRXqo1Ib94zwO
JfBJHjFToA/GqwromZgiTzJkKq5xbN8MFwIDAQABo4HSMIHPMAsGA1UdDwQEAwIF
4DA7BgNVHREENDAygRVlbWFpbEBkZW1vLm5ldGFwcC5jb22HBMCoAB+CE3ZjMS5k
ZW1vLm5ldGFwcC5jb20wHQYDVR0OBBYEFJ0V0zY+JRpFrEt31ovAY4BLFXmAMB8G
A1UdIwQYMBaAFENf6fRxWF3OJQNTPIdUpK6kjA78MEMGCCsGAQUFBwEBBDcwNTAz
BggrBgEFBQcwAoYnaHR0cHM6Ly92YzEuZGVtby5uZXRhcHAuY29tL2FmZC92ZWNz
L2NhMA0GCSqGSIb3DQEBCwUAA4IBgQBaDfk7GBM4vmhzYCqGrr6KB+h3qeTJ+Y0Y
5nIPRP1HucawDQ8QTay605ddJ8gFGoxkOQDn9tdXWXGjnTRFOT8R+Hw/nUfVSiDP
sYienb16copzUNwtqh+m9Ifow74Gf+ulRzEC0EAVO1X/nTEYH6NKM6Wy7y7F8g5J
lrpM3JY90ZChMqHO3Av/88rbErfQ/gU1brJ3u9Gks4e20Z7Ff312ZKhWRuJDlN2Z
0tc/gp90N9GxaVvELovq/pdjaZ8xiXCxa6piicrJd9WnqMH1gmxP2PIBDxMDBWBG
gwsfs5H7VG9MJYks6lViNsGclo0EwEdF0MfoB3JtsWpPWq6+jBua0Jm7/aFCU+Ht
mykr0gaV7muegoiBQuDma4EkAI31D7ZlUgJQaw157NTk4RW3TFcbtViBHJkM54Hr
iVm0cl+2BZNi/QTMh/MkWV2dYXJ3NuNlqqfzFY+bUfkzkR4SneMk0HX3joNNYDJv
siO7bL+k/Pxql27NVIhuCoVJAlcI7ak=
---{}END CERTIFICATE{}---
----
. 複製輸出結果並將其另存為文字檔案。 `.pem` 桌面擴充程式。
. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 從側邊列選取適用的 vCenter Server 執行個體
. 選取您要修改的 vCenter Server 的垂直省略符號，然後選取 * 修改 *。
. 在「修改 vCenter」視窗中，輸入使用者名稱、密碼和連接埠詳細資料。
. 上傳憑證並選取 *Modify*。


.相關資訊
link:../manage/configure-remote-diagnostic-access.html["設定遠端診斷存取"]
