---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: 在遷移資料中心內現有虛擬機器時、您應該注意一些考量事項。 
---
= ONTAP 工具的虛擬機器遷移和複製注意事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 支援所有主要類型的虛擬機器移轉，包括僅運算（vMotion）、僅儲存（Storage vMotion）以及跨所有資料存放區的運算和儲存組合移轉。本主題概述了確保虛擬機器成功移轉和複製的關鍵考量和最佳實務做法，無論底層資料存放區類型為何。



== 移轉受保護的虛擬機器

您可以將受保護的虛擬機器移轉至：

* 不同 ESXi 主機上的同一個資料存放區
* 同一 ESXi 主機上不同的相容資料存放區
* 位於不同 ESXi 主機上的不同相容資料存放區


如果將虛擬機器遷移到不同的 FlexVol Volume，系統會使用虛擬機器資訊更新該磁碟區的中繼資料檔案。如果將虛擬機器遷移到不同的 ESXi 主機但使用相同的儲存設備，則底層 FlexVol Volume 中繼資料檔案不會被修改。

如需移轉虛擬機器的相關資訊、請參閱 Broadcom 文件： https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vcenter-and-host-management/migrating-virtual-machines-host-management.html["vSphere 虛擬機器遷移"]



== 複製受保護的虛擬機器

您可以將受保護的虛擬機器複製到下列項目：

* 使用複寫群組的相同 FlexVol Volume 的相同容器
+
同一 FlexVol volume 的中繼資料檔案會更新為複製虛擬機器的詳細資料。

* 使用複寫群組的不同 FlexVol Volume 的相同容器
+
在放置複製虛擬機器的 FlexVol volume 中，中繼資料檔案會更新為複製虛擬機器的詳細資料。

* 不同的容器或 vVols 資料存放區
+
在放置複製虛擬機器的 FlexVol volume 中，中繼資料檔案會更新為虛擬機器詳細資料。



VMware 目前不支援將虛擬機器複製到 VM 範本。

支援受保護虛擬機器的複本的複本。

如需更多詳細資料、請參閱 Broadcom 文件： https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["建立虛擬機器進行複製"]



== 虛擬機器快照

ONTAP tools 透過標準的 VMware 工作流程支援虛擬機器快照。快照是短期回滾點，適用於測試和修補程式準備等用例。它們不能取代基於備份或複寫的資料保護。長時間在快照上執行虛擬機器可能會導致系統不穩定和資料遺失。

您可以對所有受支援的資料儲存類型建立崩潰一致性快照（不包含記憶體狀態的快照，可用於將虛擬機器重新啟動至一致狀態）。此外，還支援靜默快照，這種快照使用 VMware Tools 在捕獲之前將記憶體中的資料刷新到磁碟。有關快照類型和行為的概述，請參閱 https://knowledge.broadcom.com/external/article/342618/overview-of-virtual-machine-snapshots-in.html["vSphere 中的虛擬機器快照概述"]。


NOTE: 記憶體快照會擷取執行中的記憶體狀態，並暫時停用虛擬機器。ONTAP tools 工作流程不支援記憶體快照。如果虛擬機器存在記憶體快照，則必須先將其刪除，然後才能將該虛擬機器納入由 ONTAP tools 管理的一致性群組或主機叢集關係中。

在 ASA r2 儲存系統中，虛擬機器快照的行為與其他儲存類型不同。快照是唯讀的。啟動虛擬機器時，VASA Provider 會根據唯讀快照建立 LUN 並啟用 IOPS。關閉虛擬機器時，VASA Provider 會刪除 LUN 並停用 IOPS。

有關管理虛擬機器快照的資訊，請參閱 Broadcom 文件 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vsphere-virtual-machine-administration/managing-virtual-machinesvsphere-vm-admin/using-snapshots-to-manage-virtual-machinesvsphere-vm-admin.html["使用 Snapshot 管理虛擬機器"]。
