---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords: virtual machine migration considerations, ONTAP tools VM cloning guidance, VMware storage vMotion considerations, VM migration best practices 
summary: 在遷移資料中心中現有的虛擬機器之前，請先審查關鍵注意事項。 
---
= 了解 ONTAP tools 中的虛擬機器移轉和複製
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 支援所有主要類型的虛擬機器移轉，包括僅運算移轉（vMotion）、僅儲存設備移轉（Storage vMotion）以及跨所有資料存放區的運算與儲存設備組合移轉。了解這些移轉和複製的注意事項及最佳實務，有助於您無論使用何種底層資料存放區類型，都能達成成功的結果。



[[migrate-protected-virtual-machines]]
== 移轉受保護的虛擬機器

您可以將受保護的虛擬機器移轉至：

* 不同 ESXi 主機上的同一個資料存放區
* 同一 ESXi 主機上不同的相容資料存放區
* 位於不同 ESXi 主機上的不同相容資料存放區


如果將虛擬機器移轉到不同的 FlexVol Volume，系統會使用虛擬機器資訊更新該 Volume 的中繼資料檔案。如果將虛擬機器移轉到不同的 ESXi 主機但儲存設備相同，則底層 FlexVol Volume 中繼資料檔案不會修改。

有關遷移虛擬機器的資訊，請參閱 https://techdocs.broadcom.com/["Broadcom 技術文件"]



[[clone-protected-virtual-machines]]
== 複製受保護的虛擬機器

您可以將受保護的虛擬機器複製到下列項目：

* 使用複寫群組的相同 FlexVol Volume 的相同容器
+
ONTAP tools 使用複製的虛擬機器詳細資料更新同一 FlexVol Volume 的中繼資料檔案。

* 使用複寫群組的不同 FlexVol Volume 的相同容器
+
在放置複製虛擬機器的 FlexVol Volume 中，ONTAP tools 會使用複製虛擬機器的詳細資訊更新中繼資料檔案。

* 不同的容器或 vVols 資料存放區
+
在放置複製虛擬機器的 FlexVol Volume 中，ONTAP tools 會使用虛擬機器詳細資料更新中繼資料檔案。



VMware 目前不支援將虛擬機器複製到 VM 範本。

支援受保護虛擬機器的複本的複本。

如需更多詳細資料、請參閱 Broadcom 文件： https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["建立虛擬機器進行複製"]



[[virtual-machine-snapshots]]
== 虛擬機器快照

ONTAP tools 透過標準的 VMware 工作流程支援虛擬機器快照。快照是短期回滾點，適用於測試和修補程式準備等用例。它們不能取代基於備份或複寫的資料保護。長時間在快照上執行虛擬機器可能會導致系統不穩定和資料遺失。

您可以對所有受支援的資料儲存類型建立崩潰一致性快照（不包含記憶體狀態的快照，可用於將虛擬機器重新啟動至一致狀態）。此外，還支援靜默快照，這種快照使用 VMware Tools 在捕獲之前將記憶體中的資料刷新到磁碟。有關快照類型和行為的概述，請參閱 https://techdocs.broadcom.com/["Broadcom 技術文件"]。


NOTE: 記憶體快照會擷取執行中的記憶體狀態，並暫時停用虛擬機器。ONTAP tools 工作流程不支援記憶體快照。如果虛擬機器存在記憶體快照，則必須先將其刪除，然後才能將該虛擬機器納入由 ONTAP tools 管理的一致性群組或主機叢集關係中。

在 ASA r2 儲存系統中，虛擬機器快照的行為與其他儲存類型不同。快照是唯讀的。啟動虛擬機器時，VASA Provider 會根據唯讀快照建立 LUN 並啟用 IOPS。關閉虛擬機器時，VASA Provider 會刪除 LUN 並停用 IOPS。

有關管理虛擬機器快照的資訊，請參閱 https://techdocs.broadcom.com/["Broadcom 技術文件"]。
