---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: 在資料中心中移轉現有虛擬機器時，您應該注意一些考量事項。 
---
= 移轉或複製虛擬機器的考量事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移轉資料中心內現有的虛擬機器時，您應該注意到一些考量事項。



== 移轉受保護的虛擬機器

您可以將受保護的虛擬機器移轉至：

* 在不同的ESXi主機中使用相同的vVols資料存放區
* 在同一ESXi主機上有不同的相容vVols資料存放區
* 不同ESXi主機中的不同相容vVols資料存放區


如果將虛擬機器遷移到不同的FlexVol volume，系統會使用虛擬機器資訊更新該磁碟區的元資料檔案。如果虛擬機器遷移到不同的 ESXi 主機但相同的存儲，則底層FlexVol volume元資料檔案將不會被修改。



== 複製受保護的虛擬機器

您可以將受保護的虛擬機器複製到下列項目：

* 使用複寫群組的同一個FlexVol 相同的Container
+
相同FlexVol 的實體磁碟區中繼資料檔案會以複製的虛擬機器詳細資料進行更新。

* 使用複寫群組的FlexVol 不同Sof Volume的相同容器
+
將複製的虛擬機器放置在其中的實體磁碟區、會以複製的虛擬機器詳細資料來更新中繼資料檔案。FlexVol

* 不同的Container或vVols資料存放區
+
將複製的虛擬機器放置在這個實體磁碟區、中繼資料檔案會更新虛擬機器詳細資料。FlexVol



VMware 目前不支援將虛擬機器複製到 VM 範本。

支援受保護虛擬機器的複製複本。

如需詳細資訊，請參閱 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["建立虛擬機器進行複製"]。



== 虛擬機器快照

目前僅支援不含記憶體的虛擬機器快照。如果虛擬機器具有快照與記憶體、則不會將虛擬機器視為保護。

您也無法保護具有記憶體快照的未受保護的虛擬機器。對於此版本，您需要在啟用虛擬機器保護之前刪除記憶體快照。

對於採用ASA r2 儲存類型的 Windows VM，虛擬機器的快照是唯讀的。當您啟動虛擬機器時，VASA Provider 會從唯讀快照建立 LUN 並啟用 IOPS。關閉虛擬機器電源時，VASA Provider 會刪除 LUN 並停用 IOPS。
