---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords: mount NFS VMFS datastore, datastore host access, ONTAP tools datastore mounting, add datastore to ESXi host 
summary: 將主機新增至 VMware 環境後，將資料存放區裝載到其他主機上。 
---
= 在 ONTAP tools 中掛載 NFS 和 VMFS 資料存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝資料存放區可讓儲存設備存取其他主機。將主機新增至VMware環境之後、即可將資料存放區掛載到其他主機上。


NOTE: 新增主機後，請等待已排程的主機探索完成，該主機才會顯示在 ONTAP tools 中。或者，您也可以從 NetApp ONTAP tools 總覽畫面手動執行探索。如需如何將 ESXi 主機新增至 vSphere 叢集的相關資訊，請參閱 https://techdocs.broadcom.com/["Broadcom 技術文件"]。

.關於這項工作
* 視 vSphere 用戶端版本和選取的資料存放區類型而定，某些按滑鼠右鍵動作會停用或無法使用。
+
** 如果您使用的是 vSphere Client 8.0 或更新版本、則會隱藏一些按滑鼠右鍵選項。
** 從 vSphere 7.0U3 到 vSphere 8.0 版本，即使出現選項，動作仍會停用。


* 當主機叢集受到統一配置保護時，vSphere 會停用掛載資料儲存選項。
* 當具有 nconnect 的資料存放區裝載到新主機上時，如果資料存放區的 nconnect 值超過主機的設定值，ONTAP tools 會套用該資料存放區的 nconnect 值。


.步驟
. 從 vSphere Client 首頁、選取 * 主機與叢集 * 。
. 在左側導覽窗格中，選取包含主機的資料中心。
. 若要在主機或主機叢集上掛載 NFS/VMFS 資料存儲，請右鍵單擊並選擇 * NetApp ONTAP工具 * > *掛載資料儲存 *。
. 選取您要掛載的資料存放區，然後選取 * 掛載 * 。


.接下來呢？
您可以在最近的工作面板中追蹤進度。

.相關主題
link:../manage/add-vsphere-host.html["新增新的 VMware vSphere 主機"]
