---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords: manage storage backends, ONTAP backend systems, storage backend operations, VMware datastore backend configuration 
summary: 管理 ESXi 主機用於資料儲存設備的儲存設備後端。 
---
= 在 ONTAP tools 中管理儲存後端
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存後端是 ESXi 主機用於資料儲存設備的系統。您可以使用 ONTAP tools for VMware vSphere 來探索、修改和移除儲存後端。



[[discover-storage]]
== 探索儲存設備

您可以隨需執行儲存設備後端探索，而無需等待下一次排程的探索來更新儲存設備詳細資訊。對於 MetroCluster 組態，請在切換後手動執行 ONTAP tools 探索。

請遵循下列步驟、探索儲存設備的後端。

.步驟
. 登入 vSphere 用戶端。
. 在捷徑頁面中，選取外掛程式區段下方的 * NetApp ONTAP tools* 。
. 在ONTAP工具的左側窗格中，前往 *儲存後端* 並選擇一個儲存後端。
. 選擇垂直省略號選單，然後選擇 *Discover storage*。


您可以在「最近的工作」面板中追蹤進度。



[[modify-storage-backends]]
== 修改儲存設備後端

您可以修改儲存設備後端憑證或連接埠名稱。您也可以使用 ONTAP tools Manager 修改全域 ONTAP 叢集的儲存設備後端。如果憑證在 30 天或更短時間內過期，ONTAP tools 將顯示警告。請修改儲存設備後端並從 ONTAP 系統管理員上傳新憑證。

當您修改儲存後端時，ONTAP tools for VMware vSphere會執行儲存後端的發現以更新儲存詳細資訊。

請依照本節中的步驟修改儲存後端。

. 登入 vSphere 用戶端。
. 在捷徑頁面中，選取外掛程式區段下方的 * NetApp ONTAP tools* 。
. 在ONTAP工具的左側窗格中，前往 *儲存後端* 並選擇一個儲存後端。
. 選擇垂直省略號選單，然後選擇 *Modify* 以修改憑證或連接埠名稱。您可以在「最近工作」面板中追蹤進度。


使用ONTAP工具管理器修改全域ONTAP集群，如下所示。

. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 從側邊列選取儲存設備後端。
. 選取您要修改的儲存後端。
. 選擇垂直省略號選單，然後選擇 *Modify*。
. 您可以修改認證或連接埠。輸入 * 使用者名稱 * 和 * 密碼 * 以修改儲存後端。




[[remove-storage-backends]]
== 移除儲存設備後端

在刪除儲存後端之前，您必須刪除附加到該儲存後端的所有資料儲存。請依照以下步驟刪除儲存後端。

. 登入 vSphere 用戶端。
. 在捷徑頁面中，選取外掛程式區段下方的 * NetApp ONTAP tools* 。
. 在ONTAP工具的左側窗格中，前往 *儲存後端* 並選擇一個儲存後端。
. 選擇垂直省略號選單，然後選擇「移除」。確認儲存設備後端不包含任何資料儲存區。您可以在「最近工作」面板中追蹤進度。


您可以使用 ONTAP tools Manager 刪除全域 ONTAP 叢集。

. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 從側欄中選擇 * 儲存後端 * 。
. 選取您要移除的儲存後端
. 選擇垂直省略號選單，然後選擇「移除」。




[[drill-down-view-of-storage-backend]]
== 深入瞭解儲存後端

儲存設備後端頁面列出了所有儲存設備後端。您可以探索、修改和移除已新增的儲存設備後端，但無法對叢集下的單一子 SVM 執行這些操作。

選擇父集群或子集群來查看元件摘要。對於父集群，使用操作下拉選單來發現儲存、修改或刪除儲存後端。

摘要頁面提供下列詳細資料：

* 儲存後端的狀態
* 容量資訊
* 虛擬機器的基本資訊
* 證書詳細信息，例如證書狀態和到期日期。
* 網路訊息，例如網路的 IP 位址和連接埠。對於子 SVM，該資訊與父儲存後端相同。
* 儲存後端的 Privileges 允許和限制。對於子 SVM，資訊與父儲存後端相同。ONTAP 工具僅在叢集型儲存後端上顯示權限。如果將 SVM 新增為儲存後端，則不會顯示權限資訊。
* 當 SVM 或叢集的分解屬性設定為「true」時，ASA r2 系統叢集向下鑽取檢視不包含本機層索引標籤。
* 對於 ASA r2 SVM 系統，容量 portlet 不會顯示。只有當 SVM 或叢集的 disaggregated 屬性設定為「true」時，才需要容量 portlet。
* 對於 ASA R2 SVM 系統，基本資訊區段會顯示平台類型。


介面索引標籤提供有關介面的詳細資訊。

本機層索引標籤提供有關彙總清單的詳細資訊。
