---
permalink: manage/uninstall-deployment.html 
sidebar: sidebar 
keywords: uninstall ONTAP tools, remove ONTAP tools deployment, appliance decommission workflow, graceful deployment termination 
summary: 正常終止 ONTAP tools for VMware vSphere 的部署。 
---
= 解除安裝 ONTAP tools for VMware vSphere 部署
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
解除安裝 ONTAP tools for VMware vSphere 會刪除應用裝置中的資料，因此請完成以下步驟以正常關閉部署並避免意外的資料遺失。

.步驟
. 從 VMware vSphere 託管資料存放區的 ONTAP 工具移除或移動所有虛擬機器。
+
** 若要移除虛擬機器，請參閱 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["移除並重新登錄 VM 和 VM 範本"]
** 若要將它們移至非受管資料存放區，請參閱 https://techdocs.broadcom.com/["Broadcom 技術文件"]以了解使用 Storage vMotion 遷移虛擬機器的相關資訊


. link:../manage/delete-ds.html["刪除資料存放區"]在適用於 VMware vSphere 的 ONTAP 工具上建立。
. 如果您已啟用 VASA Provider，請在 ONTAP tools 中選擇 *Settings* > *VASA Provider settings* > *Unregister*，以從所有 vCenter Server 執行個體取消註冊 VASA Provider。
. 從 VMware Live Site Recovery 移除 SRA 介面卡：
+
.. 以管理員身分使用連接埠 5480 登入 VMware Live Site Recovery 應用裝置管理介面。
.. 選取 * 儲存複寫介面卡 * 。
.. 選取適當的 SRA 卡，然後從下拉式功能表中選取 * 刪除 * 。
.. 確認您知道刪除介面卡的結果，然後選取 * 刪除 * 。


. 移除已加入 ONTAP tools for VMware vSphere 的 vCenter Server 執行個體。請參閱 link:../manage/manage-vcenter.html["管理 vCenter Server 執行個體"]。
+
當您移除 vCenter Server 執行個體時，ONTAP tools 可以指南您完成所需的清理工作。如果在 *移除 vCenter* 對話方塊中出現提示，請選取 *從此 vCenter Server 移除所有儲存設備項目* 和 *我瞭解關聯的資料存放區將不再由 ONTAP tools 代管*，然後選取 *強制刪除*。

+
在使用 *Force delete* 之前，請確保所有 vVols 資料儲存都已移除或遷移，所有受保護的資料儲存都已取消保護，且沒有探索作業正在執行。

+
如果在刪除期間無法連線至 vCenter Server，ONTAP tools 只會移除 vCenter Server 記錄。您必須手動從 VMware vCenter Server 取消註冊外掛。

. 從 vCenter Server 關閉適用於 VMware vSphere VM 的 ONTAP 工具，然後刪除 VM 。


.接下來呢？
link:../manage/delete-deployment.html["移除 FlexVol Volume"]
